// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/agent_runs.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndSessionReason int32

const (
	EndSessionReason_END_SESSION_REASON_UNSPECIFIED  EndSessionReason = 0
	EndSessionReason_END_SESSION_REASON_USER_ENDED   EndSessionReason = 1
	EndSessionReason_END_SESSION_REASON_IDLE_TIMEOUT EndSessionReason = 2
	EndSessionReason_END_SESSION_REASON_CANCELLED    EndSessionReason = 3
)

// Enum value maps for EndSessionReason.
var (
	EndSessionReason_name = map[int32]string{
		0: "END_SESSION_REASON_UNSPECIFIED",
		1: "END_SESSION_REASON_USER_ENDED",
		2: "END_SESSION_REASON_IDLE_TIMEOUT",
		3: "END_SESSION_REASON_CANCELLED",
	}
	EndSessionReason_value = map[string]int32{
		"END_SESSION_REASON_UNSPECIFIED":  0,
		"END_SESSION_REASON_USER_ENDED":   1,
		"END_SESSION_REASON_IDLE_TIMEOUT": 2,
		"END_SESSION_REASON_CANCELLED":    3,
	}
)

func (x EndSessionReason) Enum() *EndSessionReason {
	p := new(EndSessionReason)
	*p = x
	return p
}

func (x EndSessionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndSessionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_agent_runs_proto_enumTypes[0].Descriptor()
}

func (EndSessionReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_agent_runs_proto_enumTypes[0]
}

func (x EndSessionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndSessionReason.Descriptor instead.
func (EndSessionReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{0}
}

// One non-terminal event of a session execution, as the Node sent it. Thread events share the
// execution's sequence space with its terminal event.
type ThreadEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Set when the record belongs to a user turn.
	TurnId *string `protobuf:"bytes,2,opt,name=turn_id,json=turnId,proto3,oneof" json:"turn_id,omitempty"`
	// One settled `ora-history` record as a JSON object, at most 256 KiB. Cloud stores it verbatim
	// and never rewrites it; an identical sequence with a different record conflicts.
	Record string `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	// The Node replaced an oversized record with a shortened one; the session history keeps the
	// original.
	Truncated     bool `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadEvent) Reset() {
	*x = ThreadEvent{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadEvent) ProtoMessage() {}

func (x *ThreadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadEvent.ProtoReflect.Descriptor instead.
func (*ThreadEvent) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{0}
}

func (x *ThreadEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ThreadEvent) GetTurnId() string {
	if x != nil && x.TurnId != nil {
		return *x.TurnId
	}
	return ""
}

func (x *ThreadEvent) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

func (x *ThreadEvent) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type TakeOverThreadEventsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch        int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The IssueRun ID.
	OperationId string `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId string `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// 1 to 64 events in ascending, gap-free sequence order. The first must be the highest sequence
	// already taken over plus one, or an already taken-over sequence with identical content (a
	// replay, skipped). A gap or different content fails with ABORTED (CONFLICT) and writes nothing.
	Events        []*ThreadEvent `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeOverThreadEventsRequest) Reset() {
	*x = TakeOverThreadEventsRequest{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverThreadEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverThreadEventsRequest) ProtoMessage() {}

func (x *TakeOverThreadEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverThreadEventsRequest.ProtoReflect.Descriptor instead.
func (*TakeOverThreadEventsRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{1}
}

func (x *TakeOverThreadEventsRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *TakeOverThreadEventsRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TakeOverThreadEventsRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *TakeOverThreadEventsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TakeOverThreadEventsRequest) GetEvents() []*ThreadEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TakeOverThreadEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest sequence of this execution Cloud has taken over, replays included.
	TakenOverThrough uint64 `protobuf:"varint,1,opt,name=taken_over_through,json=takenOverThrough,proto3" json:"taken_over_through,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TakeOverThreadEventsResponse) Reset() {
	*x = TakeOverThreadEventsResponse{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOverThreadEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverThreadEventsResponse) ProtoMessage() {}

func (x *TakeOverThreadEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverThreadEventsResponse.ProtoReflect.Descriptor instead.
func (*TakeOverThreadEventsResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{2}
}

func (x *TakeOverThreadEventsResponse) GetTakenOverThrough() uint64 {
	if x != nil {
		return x.TakenOverThrough
	}
	return 0
}

// Queues a user turn behind the one in progress; it never interrupts the current turn.
type SubmitUserTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turn          *UserTurn              `protobuf:"bytes,1,opt,name=turn,proto3" json:"turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUserTurn) Reset() {
	*x = SubmitUserTurn{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUserTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUserTurn) ProtoMessage() {}

func (x *SubmitUserTurn) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUserTurn.ProtoReflect.Descriptor instead.
func (*SubmitUserTurn) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitUserTurn) GetTurn() *UserTurn {
	if x != nil {
		return x.Turn
	}
	return nil
}

// Asks the Node to cancel the current turn, discard queued turns and end the session.
type EndSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        EndSessionReason       `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.EndSessionReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSession) Reset() {
	*x = EndSession{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSession) ProtoMessage() {}

func (x *EndSession) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSession.ProtoReflect.Descriptor instead.
func (*EndSession) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{4}
}

func (x *EndSession) GetReason() EndSessionReason {
	if x != nil {
		return x.Reason
	}
	return EndSessionReason_END_SESSION_REASON_UNSPECIFIED
}

type ThreadCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated by Cloud; the Node executes one command ID at most once.
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RunId     string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// The run's session execution, already registered through RecordDispatch.
	ExecutionId string      `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Target      *WorkTarget `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ThreadCommand_SubmitUserTurn
	//	*ThreadCommand_EndSession
	Command       isThreadCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadCommand) Reset() {
	*x = ThreadCommand{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadCommand) ProtoMessage() {}

func (x *ThreadCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadCommand.ProtoReflect.Descriptor instead.
func (*ThreadCommand) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{5}
}

func (x *ThreadCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ThreadCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ThreadCommand) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ThreadCommand) GetTarget() *WorkTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ThreadCommand) GetCommand() isThreadCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ThreadCommand) GetSubmitUserTurn() *SubmitUserTurn {
	if x != nil {
		if x, ok := x.Command.(*ThreadCommand_SubmitUserTurn); ok {
			return x.SubmitUserTurn
		}
	}
	return nil
}

func (x *ThreadCommand) GetEndSession() *EndSession {
	if x != nil {
		if x, ok := x.Command.(*ThreadCommand_EndSession); ok {
			return x.EndSession
		}
	}
	return nil
}

type isThreadCommand_Command interface {
	isThreadCommand_Command()
}

type ThreadCommand_SubmitUserTurn struct {
	SubmitUserTurn *SubmitUserTurn `protobuf:"bytes,5,opt,name=submit_user_turn,json=submitUserTurn,proto3,oneof"`
}

type ThreadCommand_EndSession struct {
	EndSession *EndSession `protobuf:"bytes,6,opt,name=end_session,json=endSession,proto3,oneof"`
}

func (*ThreadCommand_SubmitUserTurn) isThreadCommand_Command() {}

func (*ThreadCommand_EndSession) isThreadCommand_Command() {}

type ClaimThreadCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// 1 to 100.
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimThreadCommandsRequest) Reset() {
	*x = ClaimThreadCommandsRequest{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimThreadCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimThreadCommandsRequest) ProtoMessage() {}

func (x *ClaimThreadCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimThreadCommandsRequest.ProtoReflect.Descriptor instead.
func (*ClaimThreadCommandsRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimThreadCommandsRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ClaimThreadCommandsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ClaimThreadCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grouped by run and ordered by creation within a run. Commands of a run whose session execution
	// is not registered yet stay in Cloud and are not listed.
	Commands      []*ThreadCommand `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimThreadCommandsResponse) Reset() {
	*x = ClaimThreadCommandsResponse{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimThreadCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimThreadCommandsResponse) ProtoMessage() {}

func (x *ClaimThreadCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimThreadCommandsResponse.ProtoReflect.Descriptor instead.
func (*ClaimThreadCommandsResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimThreadCommandsResponse) GetCommands() []*ThreadCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RecordThreadCommandDeliveredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordThreadCommandDeliveredRequest) Reset() {
	*x = RecordThreadCommandDeliveredRequest{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordThreadCommandDeliveredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordThreadCommandDeliveredRequest) ProtoMessage() {}

func (x *RecordThreadCommandDeliveredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordThreadCommandDeliveredRequest.ProtoReflect.Descriptor instead.
func (*RecordThreadCommandDeliveredRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{8}
}

func (x *RecordThreadCommandDeliveredRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RecordThreadCommandDeliveredRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RecordThreadCommandDeliveredRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RecordThreadCommandDeliveredRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type RecordThreadCommandDeliveredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordThreadCommandDeliveredResponse) Reset() {
	*x = RecordThreadCommandDeliveredResponse{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordThreadCommandDeliveredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordThreadCommandDeliveredResponse) ProtoMessage() {}

func (x *RecordThreadCommandDeliveredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordThreadCommandDeliveredResponse.ProtoReflect.Descriptor instead.
func (*RecordThreadCommandDeliveredResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{9}
}

type GrantRevisionUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// A delivery execution registered through RecordDispatch.
	ExecutionId string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Optional object key -> lowercase hexadecimal SHA-256. Keys must belong to the frozen
	// delivery input. Cloud binds each checksum into its ephemeral PUT signature; refreshing
	// this capability never changes the execution input. Omit for legacy v1 grants.
	Checksums     map[string]string `protobuf:"bytes,3,rep,name=checksums,proto3" json:"checksums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRevisionUploadRequest) Reset() {
	*x = GrantRevisionUploadRequest{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRevisionUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRevisionUploadRequest) ProtoMessage() {}

func (x *GrantRevisionUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRevisionUploadRequest.ProtoReflect.Descriptor instead.
func (*GrantRevisionUploadRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{10}
}

func (x *GrantRevisionUploadRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GrantRevisionUploadRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GrantRevisionUploadRequest) GetChecksums() map[string]string {
	if x != nil {
		return x.Checksums
	}
	return nil
}

type GrantRevisionUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One grant per requested checksum key, or both input keys for legacy requests.
	Grants        []*UploadGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRevisionUploadResponse) Reset() {
	*x = GrantRevisionUploadResponse{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRevisionUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRevisionUploadResponse) ProtoMessage() {}

func (x *GrantRevisionUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRevisionUploadResponse.ProtoReflect.Descriptor instead.
func (*GrantRevisionUploadResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{11}
}

func (x *GrantRevisionUploadResponse) GetGrants() []*UploadGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type GrantRevisionDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// A session execution registered through RecordDispatch whose input carries prior_revision.
	ExecutionId   string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRevisionDownloadRequest) Reset() {
	*x = GrantRevisionDownloadRequest{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRevisionDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRevisionDownloadRequest) ProtoMessage() {}

func (x *GrantRevisionDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRevisionDownloadRequest.ProtoReflect.Descriptor instead.
func (*GrantRevisionDownloadRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{12}
}

func (x *GrantRevisionDownloadRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GrantRevisionDownloadRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GrantRevisionDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one grant, for the input's prior_revision bundle key.
	Grants        []*DownloadGrant `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRevisionDownloadResponse) Reset() {
	*x = GrantRevisionDownloadResponse{}
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRevisionDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRevisionDownloadResponse) ProtoMessage() {}

func (x *GrantRevisionDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRevisionDownloadResponse.ProtoReflect.Descriptor instead.
func (*GrantRevisionDownloadResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP(), []int{13}
}

func (x *GrantRevisionDownloadResponse) GetGrants() []*DownloadGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

var File_ora_cloud_internal_v1_agent_runs_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_agent_runs_proto_rawDesc = "" +
	"\n" +
	"&ora/cloud/internal/v1/agent_runs.proto\x12\x15ora.cloud.internal.v1\x1a,ora/cloud/internal/v1/agent_executions.proto\x1a&ora/cloud/internal/v1/executions.proto\"\x89\x01\n" +
	"\vThreadEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1c\n" +
	"\aturn_id\x18\x02 \x01(\tH\x00R\x06turnId\x88\x01\x01\x12\x16\n" +
	"\x06record\x18\x03 \x01(\tR\x06record\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncatedB\n" +
	"\n" +
	"\b_turn_id\"\xda\x01\n" +
	"\x1bTakeOverThreadEventsRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12:\n" +
	"\x06events\x18\x05 \x03(\v2\".ora.cloud.internal.v1.ThreadEventR\x06events\"L\n" +
	"\x1cTakeOverThreadEventsResponse\x12,\n" +
	"\x12taken_over_through\x18\x01 \x01(\x04R\x10takenOverThrough\"E\n" +
	"\x0eSubmitUserTurn\x123\n" +
	"\x04turn\x18\x01 \x01(\v2\x1f.ora.cloud.internal.v1.UserTurnR\x04turn\"M\n" +
	"\n" +
	"EndSession\x12?\n" +
	"\x06reason\x18\x01 \x01(\x0e2'.ora.cloud.internal.v1.EndSessionReasonR\x06reason\"\xc7\x02\n" +
	"\rThreadCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x129\n" +
	"\x06target\x18\x04 \x01(\v2!.ora.cloud.internal.v1.WorkTargetR\x06target\x12Q\n" +
	"\x10submit_user_turn\x18\x05 \x01(\v2%.ora.cloud.internal.v1.SubmitUserTurnH\x00R\x0esubmitUserTurn\x12D\n" +
	"\vend_session\x18\x06 \x01(\v2!.ora.cloud.internal.v1.EndSessionH\x00R\n" +
	"endSessionB\t\n" +
	"\acommand\"H\n" +
	"\x1aClaimThreadCommandsRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"_\n" +
	"\x1bClaimThreadCommandsResponse\x12@\n" +
	"\bcommands\x18\x01 \x03(\v2$.ora.cloud.internal.v1.ThreadCommandR\bcommands\"\xa2\x01\n" +
	"#RecordThreadCommandDeliveredRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\"&\n" +
	"$RecordThreadCommandDeliveredResponse\"\xf3\x01\n" +
	"\x1aGrantRevisionUploadRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12^\n" +
	"\tchecksums\x18\x03 \x03(\v2@.ora.cloud.internal.v1.GrantRevisionUploadRequest.ChecksumsEntryR\tchecksums\x1a<\n" +
	"\x0eChecksumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x1bGrantRevisionUploadResponse\x12:\n" +
	"\x06grants\x18\x01 \x03(\v2\".ora.cloud.internal.v1.UploadGrantR\x06grants\"W\n" +
	"\x1cGrantRevisionDownloadRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\"]\n" +
	"\x1dGrantRevisionDownloadResponse\x12<\n" +
	"\x06grants\x18\x01 \x03(\v2$.ora.cloud.internal.v1.DownloadGrantR\x06grants*\xa0\x01\n" +
	"\x10EndSessionReason\x12\"\n" +
	"\x1eEND_SESSION_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dEND_SESSION_REASON_USER_ENDED\x10\x01\x12#\n" +
	"\x1fEND_SESSION_REASON_IDLE_TIMEOUT\x10\x02\x12 \n" +
	"\x1cEND_SESSION_REASON_CANCELLED\x10\x032\xad\x05\n" +
	"\x0fAgentRunService\x12\x7f\n" +
	"\x14TakeOverThreadEvents\x122.ora.cloud.internal.v1.TakeOverThreadEventsRequest\x1a3.ora.cloud.internal.v1.TakeOverThreadEventsResponse\x12|\n" +
	"\x13ClaimThreadCommands\x121.ora.cloud.internal.v1.ClaimThreadCommandsRequest\x1a2.ora.cloud.internal.v1.ClaimThreadCommandsResponse\x12\x97\x01\n" +
	"\x1cRecordThreadCommandDelivered\x12:.ora.cloud.internal.v1.RecordThreadCommandDeliveredRequest\x1a;.ora.cloud.internal.v1.RecordThreadCommandDeliveredResponse\x12|\n" +
	"\x13GrantRevisionUpload\x121.ora.cloud.internal.v1.GrantRevisionUploadRequest\x1a2.ora.cloud.internal.v1.GrantRevisionUploadResponse\x12\x82\x01\n" +
	"\x15GrantRevisionDownload\x123.ora.cloud.internal.v1.GrantRevisionDownloadRequest\x1a4.ora.cloud.internal.v1.GrantRevisionDownloadResponseB\xdf\x01\n" +
	"\x19com.ora.cloud.internal.v1B\x0eAgentRunsProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_agent_runs_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_agent_runs_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_agent_runs_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_agent_runs_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_agent_runs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_agent_runs_proto_rawDesc), len(file_ora_cloud_internal_v1_agent_runs_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_agent_runs_proto_rawDescData
}

var file_ora_cloud_internal_v1_agent_runs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ora_cloud_internal_v1_agent_runs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ora_cloud_internal_v1_agent_runs_proto_goTypes = []any{
	(EndSessionReason)(0),                        // 0: ora.cloud.internal.v1.EndSessionReason
	(*ThreadEvent)(nil),                          // 1: ora.cloud.internal.v1.ThreadEvent
	(*TakeOverThreadEventsRequest)(nil),          // 2: ora.cloud.internal.v1.TakeOverThreadEventsRequest
	(*TakeOverThreadEventsResponse)(nil),         // 3: ora.cloud.internal.v1.TakeOverThreadEventsResponse
	(*SubmitUserTurn)(nil),                       // 4: ora.cloud.internal.v1.SubmitUserTurn
	(*EndSession)(nil),                           // 5: ora.cloud.internal.v1.EndSession
	(*ThreadCommand)(nil),                        // 6: ora.cloud.internal.v1.ThreadCommand
	(*ClaimThreadCommandsRequest)(nil),           // 7: ora.cloud.internal.v1.ClaimThreadCommandsRequest
	(*ClaimThreadCommandsResponse)(nil),          // 8: ora.cloud.internal.v1.ClaimThreadCommandsResponse
	(*RecordThreadCommandDeliveredRequest)(nil),  // 9: ora.cloud.internal.v1.RecordThreadCommandDeliveredRequest
	(*RecordThreadCommandDeliveredResponse)(nil), // 10: ora.cloud.internal.v1.RecordThreadCommandDeliveredResponse
	(*GrantRevisionUploadRequest)(nil),           // 11: ora.cloud.internal.v1.GrantRevisionUploadRequest
	(*GrantRevisionUploadResponse)(nil),          // 12: ora.cloud.internal.v1.GrantRevisionUploadResponse
	(*GrantRevisionDownloadRequest)(nil),         // 13: ora.cloud.internal.v1.GrantRevisionDownloadRequest
	(*GrantRevisionDownloadResponse)(nil),        // 14: ora.cloud.internal.v1.GrantRevisionDownloadResponse
	nil,                                          // 15: ora.cloud.internal.v1.GrantRevisionUploadRequest.ChecksumsEntry
	(*UserTurn)(nil),                             // 16: ora.cloud.internal.v1.UserTurn
	(*WorkTarget)(nil),                           // 17: ora.cloud.internal.v1.WorkTarget
	(*UploadGrant)(nil),                          // 18: ora.cloud.internal.v1.UploadGrant
	(*DownloadGrant)(nil),                        // 19: ora.cloud.internal.v1.DownloadGrant
}
var file_ora_cloud_internal_v1_agent_runs_proto_depIdxs = []int32{
	1,  // 0: ora.cloud.internal.v1.TakeOverThreadEventsRequest.events:type_name -> ora.cloud.internal.v1.ThreadEvent
	16, // 1: ora.cloud.internal.v1.SubmitUserTurn.turn:type_name -> ora.cloud.internal.v1.UserTurn
	0,  // 2: ora.cloud.internal.v1.EndSession.reason:type_name -> ora.cloud.internal.v1.EndSessionReason
	17, // 3: ora.cloud.internal.v1.ThreadCommand.target:type_name -> ora.cloud.internal.v1.WorkTarget
	4,  // 4: ora.cloud.internal.v1.ThreadCommand.submit_user_turn:type_name -> ora.cloud.internal.v1.SubmitUserTurn
	5,  // 5: ora.cloud.internal.v1.ThreadCommand.end_session:type_name -> ora.cloud.internal.v1.EndSession
	6,  // 6: ora.cloud.internal.v1.ClaimThreadCommandsResponse.commands:type_name -> ora.cloud.internal.v1.ThreadCommand
	15, // 7: ora.cloud.internal.v1.GrantRevisionUploadRequest.checksums:type_name -> ora.cloud.internal.v1.GrantRevisionUploadRequest.ChecksumsEntry
	18, // 8: ora.cloud.internal.v1.GrantRevisionUploadResponse.grants:type_name -> ora.cloud.internal.v1.UploadGrant
	19, // 9: ora.cloud.internal.v1.GrantRevisionDownloadResponse.grants:type_name -> ora.cloud.internal.v1.DownloadGrant
	2,  // 10: ora.cloud.internal.v1.AgentRunService.TakeOverThreadEvents:input_type -> ora.cloud.internal.v1.TakeOverThreadEventsRequest
	7,  // 11: ora.cloud.internal.v1.AgentRunService.ClaimThreadCommands:input_type -> ora.cloud.internal.v1.ClaimThreadCommandsRequest
	9,  // 12: ora.cloud.internal.v1.AgentRunService.RecordThreadCommandDelivered:input_type -> ora.cloud.internal.v1.RecordThreadCommandDeliveredRequest
	11, // 13: ora.cloud.internal.v1.AgentRunService.GrantRevisionUpload:input_type -> ora.cloud.internal.v1.GrantRevisionUploadRequest
	13, // 14: ora.cloud.internal.v1.AgentRunService.GrantRevisionDownload:input_type -> ora.cloud.internal.v1.GrantRevisionDownloadRequest
	3,  // 15: ora.cloud.internal.v1.AgentRunService.TakeOverThreadEvents:output_type -> ora.cloud.internal.v1.TakeOverThreadEventsResponse
	8,  // 16: ora.cloud.internal.v1.AgentRunService.ClaimThreadCommands:output_type -> ora.cloud.internal.v1.ClaimThreadCommandsResponse
	10, // 17: ora.cloud.internal.v1.AgentRunService.RecordThreadCommandDelivered:output_type -> ora.cloud.internal.v1.RecordThreadCommandDeliveredResponse
	12, // 18: ora.cloud.internal.v1.AgentRunService.GrantRevisionUpload:output_type -> ora.cloud.internal.v1.GrantRevisionUploadResponse
	14, // 19: ora.cloud.internal.v1.AgentRunService.GrantRevisionDownload:output_type -> ora.cloud.internal.v1.GrantRevisionDownloadResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_agent_runs_proto_init() }
func file_ora_cloud_internal_v1_agent_runs_proto_init() {
	if File_ora_cloud_internal_v1_agent_runs_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_agent_executions_proto_init()
	file_ora_cloud_internal_v1_executions_proto_init()
	file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[0].OneofWrappers = []any{}
	file_ora_cloud_internal_v1_agent_runs_proto_msgTypes[5].OneofWrappers = []any{
		(*ThreadCommand_SubmitUserTurn)(nil),
		(*ThreadCommand_EndSession)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_agent_runs_proto_rawDesc), len(file_ora_cloud_internal_v1_agent_runs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_agent_runs_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_agent_runs_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_agent_runs_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_agent_runs_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_agent_runs_proto = out.File
	file_ora_cloud_internal_v1_agent_runs_proto_goTypes = nil
	file_ora_cloud_internal_v1_agent_runs_proto_depIdxs = nil
}
