// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/agent_runs.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRunService_TakeOverThreadEvents_FullMethodName         = "/ora.cloud.internal.v1.AgentRunService/TakeOverThreadEvents"
	AgentRunService_ClaimThreadCommands_FullMethodName          = "/ora.cloud.internal.v1.AgentRunService/ClaimThreadCommands"
	AgentRunService_RecordThreadCommandDelivered_FullMethodName = "/ora.cloud.internal.v1.AgentRunService/RecordThreadCommandDelivered"
	AgentRunService_GrantRevisionUpload_FullMethodName          = "/ora.cloud.internal.v1.AgentRunService/GrantRevisionUpload"
	AgentRunService_GrantRevisionDownload_FullMethodName        = "/ora.cloud.internal.v1.AgentRunService/GrantRevisionDownload"
)

// AgentRunServiceClient is the client API for AgentRunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// What an Agent IssueRun needs beyond ExecutionService: the session execution's non-terminal
// Thread events, Thread commands (user turns and end requests) Cloud persisted for the Node, and
// upload grants for a delivery execution. Writes carry `submission_id` with the same replay rules as
// ExecutionService and are fenced by the caller's lease `epoch`.
type AgentRunServiceClient interface {
	// Takes over a contiguous batch of Thread events of one session execution in one transaction.
	// Only after this succeeds may the Controller acknowledge those sequences to the Node.
	TakeOverThreadEvents(ctx context.Context, in *TakeOverThreadEventsRequest, opts ...grpc.CallOption) (*TakeOverThreadEventsResponse, error)
	// Lists Thread commands not yet recorded as delivered. Read-only; it claims nothing.
	ClaimThreadCommands(ctx context.Context, in *ClaimThreadCommandsRequest, opts ...grpc.CallOption) (*ClaimThreadCommandsResponse, error)
	// Records that the Node durably accepted (or refused as ended) a command; it is not listed again.
	RecordThreadCommandDelivered(ctx context.Context, in *RecordThreadCommandDeliveredRequest, opts ...grpc.CallOption) (*RecordThreadCommandDeliveredResponse, error)
	// Issues fresh upload grants for a registered delivery execution that has no result yet. Not a
	// write: nothing is recorded, and every call issues new grants.
	GrantRevisionUpload(ctx context.Context, in *GrantRevisionUploadRequest, opts ...grpc.CallOption) (*GrantRevisionUploadResponse, error)
	// Issues a fresh read grant for the prior Revision bundle of a registered session execution that
	// has no result yet. Not a write: nothing is recorded, and every call issues a new grant.
	GrantRevisionDownload(ctx context.Context, in *GrantRevisionDownloadRequest, opts ...grpc.CallOption) (*GrantRevisionDownloadResponse, error)
}

type agentRunServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRunServiceClient(cc grpc.ClientConnInterface) AgentRunServiceClient {
	return &agentRunServiceClient{cc}
}

func (c *agentRunServiceClient) TakeOverThreadEvents(ctx context.Context, in *TakeOverThreadEventsRequest, opts ...grpc.CallOption) (*TakeOverThreadEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeOverThreadEventsResponse)
	err := c.cc.Invoke(ctx, AgentRunService_TakeOverThreadEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunServiceClient) ClaimThreadCommands(ctx context.Context, in *ClaimThreadCommandsRequest, opts ...grpc.CallOption) (*ClaimThreadCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimThreadCommandsResponse)
	err := c.cc.Invoke(ctx, AgentRunService_ClaimThreadCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunServiceClient) RecordThreadCommandDelivered(ctx context.Context, in *RecordThreadCommandDeliveredRequest, opts ...grpc.CallOption) (*RecordThreadCommandDeliveredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordThreadCommandDeliveredResponse)
	err := c.cc.Invoke(ctx, AgentRunService_RecordThreadCommandDelivered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunServiceClient) GrantRevisionUpload(ctx context.Context, in *GrantRevisionUploadRequest, opts ...grpc.CallOption) (*GrantRevisionUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRevisionUploadResponse)
	err := c.cc.Invoke(ctx, AgentRunService_GrantRevisionUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRunServiceClient) GrantRevisionDownload(ctx context.Context, in *GrantRevisionDownloadRequest, opts ...grpc.CallOption) (*GrantRevisionDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRevisionDownloadResponse)
	err := c.cc.Invoke(ctx, AgentRunService_GrantRevisionDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRunServiceServer is the server API for AgentRunService service.
// All implementations must embed UnimplementedAgentRunServiceServer
// for forward compatibility.
//
// What an Agent IssueRun needs beyond ExecutionService: the session execution's non-terminal
// Thread events, Thread commands (user turns and end requests) Cloud persisted for the Node, and
// upload grants for a delivery execution. Writes carry `submission_id` with the same replay rules as
// ExecutionService and are fenced by the caller's lease `epoch`.
type AgentRunServiceServer interface {
	// Takes over a contiguous batch of Thread events of one session execution in one transaction.
	// Only after this succeeds may the Controller acknowledge those sequences to the Node.
	TakeOverThreadEvents(context.Context, *TakeOverThreadEventsRequest) (*TakeOverThreadEventsResponse, error)
	// Lists Thread commands not yet recorded as delivered. Read-only; it claims nothing.
	ClaimThreadCommands(context.Context, *ClaimThreadCommandsRequest) (*ClaimThreadCommandsResponse, error)
	// Records that the Node durably accepted (or refused as ended) a command; it is not listed again.
	RecordThreadCommandDelivered(context.Context, *RecordThreadCommandDeliveredRequest) (*RecordThreadCommandDeliveredResponse, error)
	// Issues fresh upload grants for a registered delivery execution that has no result yet. Not a
	// write: nothing is recorded, and every call issues new grants.
	GrantRevisionUpload(context.Context, *GrantRevisionUploadRequest) (*GrantRevisionUploadResponse, error)
	// Issues a fresh read grant for the prior Revision bundle of a registered session execution that
	// has no result yet. Not a write: nothing is recorded, and every call issues a new grant.
	GrantRevisionDownload(context.Context, *GrantRevisionDownloadRequest) (*GrantRevisionDownloadResponse, error)
	mustEmbedUnimplementedAgentRunServiceServer()
}

// UnimplementedAgentRunServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRunServiceServer struct{}

func (UnimplementedAgentRunServiceServer) TakeOverThreadEvents(context.Context, *TakeOverThreadEventsRequest) (*TakeOverThreadEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeOverThreadEvents not implemented")
}
func (UnimplementedAgentRunServiceServer) ClaimThreadCommands(context.Context, *ClaimThreadCommandsRequest) (*ClaimThreadCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimThreadCommands not implemented")
}
func (UnimplementedAgentRunServiceServer) RecordThreadCommandDelivered(context.Context, *RecordThreadCommandDeliveredRequest) (*RecordThreadCommandDeliveredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordThreadCommandDelivered not implemented")
}
func (UnimplementedAgentRunServiceServer) GrantRevisionUpload(context.Context, *GrantRevisionUploadRequest) (*GrantRevisionUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantRevisionUpload not implemented")
}
func (UnimplementedAgentRunServiceServer) GrantRevisionDownload(context.Context, *GrantRevisionDownloadRequest) (*GrantRevisionDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantRevisionDownload not implemented")
}
func (UnimplementedAgentRunServiceServer) mustEmbedUnimplementedAgentRunServiceServer() {}
func (UnimplementedAgentRunServiceServer) testEmbeddedByValue()                         {}

// UnsafeAgentRunServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRunServiceServer will
// result in compilation errors.
type UnsafeAgentRunServiceServer interface {
	mustEmbedUnimplementedAgentRunServiceServer()
}

func RegisterAgentRunServiceServer(s grpc.ServiceRegistrar, srv AgentRunServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentRunServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRunService_ServiceDesc, srv)
}

func _AgentRunService_TakeOverThreadEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeOverThreadEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunServiceServer).TakeOverThreadEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunService_TakeOverThreadEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunServiceServer).TakeOverThreadEvents(ctx, req.(*TakeOverThreadEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunService_ClaimThreadCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimThreadCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunServiceServer).ClaimThreadCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunService_ClaimThreadCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunServiceServer).ClaimThreadCommands(ctx, req.(*ClaimThreadCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunService_RecordThreadCommandDelivered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordThreadCommandDeliveredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunServiceServer).RecordThreadCommandDelivered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunService_RecordThreadCommandDelivered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunServiceServer).RecordThreadCommandDelivered(ctx, req.(*RecordThreadCommandDeliveredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunService_GrantRevisionUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRevisionUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunServiceServer).GrantRevisionUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunService_GrantRevisionUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunServiceServer).GrantRevisionUpload(ctx, req.(*GrantRevisionUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRunService_GrantRevisionDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRevisionDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRunServiceServer).GrantRevisionDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRunService_GrantRevisionDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRunServiceServer).GrantRevisionDownload(ctx, req.(*GrantRevisionDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRunService_ServiceDesc is the grpc.ServiceDesc for AgentRunService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRunService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.AgentRunService",
	HandlerType: (*AgentRunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeOverThreadEvents",
			Handler:    _AgentRunService_TakeOverThreadEvents_Handler,
		},
		{
			MethodName: "ClaimThreadCommands",
			Handler:    _AgentRunService_ClaimThreadCommands_Handler,
		},
		{
			MethodName: "RecordThreadCommandDelivered",
			Handler:    _AgentRunService_RecordThreadCommandDelivered_Handler,
		},
		{
			MethodName: "GrantRevisionUpload",
			Handler:    _AgentRunService_GrantRevisionUpload_Handler,
		},
		{
			MethodName: "GrantRevisionDownload",
			Handler:    _AgentRunService_GrantRevisionDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/agent_runs.proto",
}
