// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/agent_executions.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSessionEndReason int32

const (
	AgentSessionEndReason_AGENT_SESSION_END_REASON_UNSPECIFIED  AgentSessionEndReason = 0
	AgentSessionEndReason_AGENT_SESSION_END_REASON_USER_ENDED   AgentSessionEndReason = 1
	AgentSessionEndReason_AGENT_SESSION_END_REASON_IDLE_TIMEOUT AgentSessionEndReason = 2
	AgentSessionEndReason_AGENT_SESSION_END_REASON_CANCELLED    AgentSessionEndReason = 3
	// The agent plugin was unavailable or its runtime gave up; `detail` names the cause.
	AgentSessionEndReason_AGENT_SESSION_END_REASON_AGENT_FAILED AgentSessionEndReason = 4
	// The Node restarted; the session record was sealed and the Workspace kept.
	AgentSessionEndReason_AGENT_SESSION_END_REASON_INTERRUPTED AgentSessionEndReason = 5
)

// Enum value maps for AgentSessionEndReason.
var (
	AgentSessionEndReason_name = map[int32]string{
		0: "AGENT_SESSION_END_REASON_UNSPECIFIED",
		1: "AGENT_SESSION_END_REASON_USER_ENDED",
		2: "AGENT_SESSION_END_REASON_IDLE_TIMEOUT",
		3: "AGENT_SESSION_END_REASON_CANCELLED",
		4: "AGENT_SESSION_END_REASON_AGENT_FAILED",
		5: "AGENT_SESSION_END_REASON_INTERRUPTED",
	}
	AgentSessionEndReason_value = map[string]int32{
		"AGENT_SESSION_END_REASON_UNSPECIFIED":  0,
		"AGENT_SESSION_END_REASON_USER_ENDED":   1,
		"AGENT_SESSION_END_REASON_IDLE_TIMEOUT": 2,
		"AGENT_SESSION_END_REASON_CANCELLED":    3,
		"AGENT_SESSION_END_REASON_AGENT_FAILED": 4,
		"AGENT_SESSION_END_REASON_INTERRUPTED":  5,
	}
)

func (x AgentSessionEndReason) Enum() *AgentSessionEndReason {
	p := new(AgentSessionEndReason)
	*p = x
	return p
}

func (x AgentSessionEndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentSessionEndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_agent_executions_proto_enumTypes[0].Descriptor()
}

func (AgentSessionEndReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_agent_executions_proto_enumTypes[0]
}

func (x AgentSessionEndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentSessionEndReason.Descriptor instead.
func (AgentSessionEndReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{0}
}

type RevisionFailureReason int32

const (
	RevisionFailureReason_REVISION_FAILURE_REASON_UNSPECIFIED          RevisionFailureReason = 0
	RevisionFailureReason_REVISION_FAILURE_REASON_SESSION_NOT_SETTLED  RevisionFailureReason = 1
	RevisionFailureReason_REVISION_FAILURE_REASON_CHECKOUT_UNAVAILABLE RevisionFailureReason = 2
	RevisionFailureReason_REVISION_FAILURE_REASON_SNAPSHOT_FAILED      RevisionFailureReason = 3
	RevisionFailureReason_REVISION_FAILURE_REASON_BUNDLE_FAILED        RevisionFailureReason = 4
	RevisionFailureReason_REVISION_FAILURE_REASON_HISTORY_UNAVAILABLE  RevisionFailureReason = 5
	RevisionFailureReason_REVISION_FAILURE_REASON_UPLOAD_FAILED        RevisionFailureReason = 6
	// Recorded by Cloud when the declared objects are missing or differ; a Node never reports it.
	RevisionFailureReason_REVISION_FAILURE_REASON_VERIFICATION_FAILED RevisionFailureReason = 7
)

// Enum value maps for RevisionFailureReason.
var (
	RevisionFailureReason_name = map[int32]string{
		0: "REVISION_FAILURE_REASON_UNSPECIFIED",
		1: "REVISION_FAILURE_REASON_SESSION_NOT_SETTLED",
		2: "REVISION_FAILURE_REASON_CHECKOUT_UNAVAILABLE",
		3: "REVISION_FAILURE_REASON_SNAPSHOT_FAILED",
		4: "REVISION_FAILURE_REASON_BUNDLE_FAILED",
		5: "REVISION_FAILURE_REASON_HISTORY_UNAVAILABLE",
		6: "REVISION_FAILURE_REASON_UPLOAD_FAILED",
		7: "REVISION_FAILURE_REASON_VERIFICATION_FAILED",
	}
	RevisionFailureReason_value = map[string]int32{
		"REVISION_FAILURE_REASON_UNSPECIFIED":          0,
		"REVISION_FAILURE_REASON_SESSION_NOT_SETTLED":  1,
		"REVISION_FAILURE_REASON_CHECKOUT_UNAVAILABLE": 2,
		"REVISION_FAILURE_REASON_SNAPSHOT_FAILED":      3,
		"REVISION_FAILURE_REASON_BUNDLE_FAILED":        4,
		"REVISION_FAILURE_REASON_HISTORY_UNAVAILABLE":  5,
		"REVISION_FAILURE_REASON_UPLOAD_FAILED":        6,
		"REVISION_FAILURE_REASON_VERIFICATION_FAILED":  7,
	}
)

func (x RevisionFailureReason) Enum() *RevisionFailureReason {
	p := new(RevisionFailureReason)
	*p = x
	return p
}

func (x RevisionFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevisionFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_agent_executions_proto_enumTypes[1].Descriptor()
}

func (RevisionFailureReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_agent_executions_proto_enumTypes[1]
}

func (x RevisionFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevisionFailureReason.Descriptor instead.
func (RevisionFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{1}
}

// Commit identity the Node exports to the Agent's process tree as GIT_AUTHOR_* and GIT_COMMITTER_*;
// snapshotted when the run was created. It is never written to a Git configuration.
type GitIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitIdentity) Reset() {
	*x = GitIdentity{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitIdentity) ProtoMessage() {}

func (x *GitIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitIdentity.ProtoReflect.Descriptor instead.
func (*GitIdentity) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{0}
}

func (x *GitIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GitIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{1}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// One block of user content handed to the Agent; only text in the first version.
type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_Text
	Block         isContentBlock_Block `protobuf_oneof:"block"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{2}
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_Text); ok {
			return x.Text
		}
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

func (*ContentBlock_Text) isContentBlock_Block() {}

// One user turn of a Thread. `turn_id` is generated by Cloud and carried into the Node's user
// message record so Cloud can mark the turn delivered.
type UserTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnId        string                 `protobuf:"bytes,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Content       []*ContentBlock        `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTurn) Reset() {
	*x = UserTurn{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTurn) ProtoMessage() {}

func (x *UserTurn) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTurn.ProtoReflect.Descriptor instead.
func (*UserTurn) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{3}
}

func (x *UserTurn) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *UserTurn) GetContent() []*ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

// The Revision a new run of the same Issue resumes from (IssueRun resume decision D1). On a session
// spec it names the verified object holding the bundle, which may belong to an earlier Revision the
// resumed one reused; on a delivery spec it carries only the identity and final commit.
type PriorRevision struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RevisionId  string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	FinalCommit string                 `protobuf:"bytes,2,opt,name=final_commit,json=finalCommit,proto3" json:"final_commit,omitempty"`
	// Set on AgentSessionSpec only. The download grant covers exactly this object key.
	Bundle        *StoredObject `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorRevision) Reset() {
	*x = PriorRevision{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorRevision) ProtoMessage() {}

func (x *PriorRevision) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorRevision.ProtoReflect.Descriptor instead.
func (*PriorRevision) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{4}
}

func (x *PriorRevision) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *PriorRevision) GetFinalCommit() string {
	if x != nil {
		return x.FinalCommit
	}
	return ""
}

func (x *PriorRevision) GetBundle() *StoredObject {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type AgentSessionSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical Plugin ID and exact version of the agent plugin installed in the Workspace.
	AgentPluginId      string `protobuf:"bytes,1,opt,name=agent_plugin_id,json=agentPluginId,proto3" json:"agent_plugin_id,omitempty"`
	AgentPluginVersion string `protobuf:"bytes,2,opt,name=agent_plugin_version,json=agentPluginVersion,proto3" json:"agent_plugin_version,omitempty"`
	// A successful clone execution of the run Workspace on the same Node.
	CheckoutExecutionId string       `protobuf:"bytes,3,opt,name=checkout_execution_id,json=checkoutExecutionId,proto3" json:"checkout_execution_id,omitempty"`
	GitIdentity         *GitIdentity `protobuf:"bytes,4,opt,name=git_identity,json=gitIdentity,proto3" json:"git_identity,omitempty"`
	// The prompt Cloud rendered from the Issue; later turns arrive as Thread commands.
	InitialTurn *UserTurn `protobuf:"bytes,5,opt,name=initial_turn,json=initialTurn,proto3" json:"initial_turn,omitempty"`
	// Set when the run resumes an earlier Revision of its Issue. The Node restores it into the checkout
	// before starting the agent and needs a Node capable of restore; if restore fails the session ends
	// AGENT_FAILED with detail `prior_revision_unavailable` or `prior_revision_base_unavailable`.
	PriorRevision *PriorRevision `protobuf:"bytes,6,opt,name=prior_revision,json=priorRevision,proto3" json:"prior_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionSpec) Reset() {
	*x = AgentSessionSpec{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionSpec) ProtoMessage() {}

func (x *AgentSessionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionSpec.ProtoReflect.Descriptor instead.
func (*AgentSessionSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{5}
}

func (x *AgentSessionSpec) GetAgentPluginId() string {
	if x != nil {
		return x.AgentPluginId
	}
	return ""
}

func (x *AgentSessionSpec) GetAgentPluginVersion() string {
	if x != nil {
		return x.AgentPluginVersion
	}
	return ""
}

func (x *AgentSessionSpec) GetCheckoutExecutionId() string {
	if x != nil {
		return x.CheckoutExecutionId
	}
	return ""
}

func (x *AgentSessionSpec) GetGitIdentity() *GitIdentity {
	if x != nil {
		return x.GitIdentity
	}
	return nil
}

func (x *AgentSessionSpec) GetInitialTurn() *UserTurn {
	if x != nil {
		return x.InitialTurn
	}
	return nil
}

func (x *AgentSessionSpec) GetPriorRevision() *PriorRevision {
	if x != nil {
		return x.PriorRevision
	}
	return nil
}

// The only terminal result of a session execution. It is taken over only after every Thread event
// before it, so the Thread's last entry lands before the session is known to have ended.
type AgentSessionEnded struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason AgentSessionEndReason  `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.AgentSessionEndReason" json:"reason,omitempty"`
	// Bounded code such as `agent_plugin_unavailable`; never raw Agent output.
	Detail        *string `protobuf:"bytes,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionEnded) Reset() {
	*x = AgentSessionEnded{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionEnded) ProtoMessage() {}

func (x *AgentSessionEnded) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionEnded.ProtoReflect.Descriptor instead.
func (*AgentSessionEnded) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{6}
}

func (x *AgentSessionEnded) GetReason() AgentSessionEndReason {
	if x != nil {
		return x.Reason
	}
	return AgentSessionEndReason_AGENT_SESSION_END_REASON_UNSPECIFIED
}

func (x *AgentSessionEnded) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

type DeliverRevisionSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ended session whose Workspace and history are saved.
	SessionExecutionId  string `protobuf:"bytes,1,opt,name=session_execution_id,json=sessionExecutionId,proto3" json:"session_execution_id,omitempty"`
	CheckoutExecutionId string `protobuf:"bytes,2,opt,name=checkout_execution_id,json=checkoutExecutionId,proto3" json:"checkout_execution_id,omitempty"`
	// Commit of the run Workspace's clone; the bundle is relative to it.
	BaseCommit string `protobuf:"bytes,3,opt,name=base_commit,json=baseCommit,proto3" json:"base_commit,omitempty"`
	// Must be under `refs/ora/revisions/`.
	RevisionRef string `protobuf:"bytes,4,opt,name=revision_ref,json=revisionRef,proto3" json:"revision_ref,omitempty"`
	// Object keys Cloud chose for this delivery; upload grants are issued only for these keys.
	BundleKey  string `protobuf:"bytes,5,opt,name=bundle_key,json=bundleKey,proto3" json:"bundle_key,omitempty"`
	HistoryKey string `protobuf:"bytes,6,opt,name=history_key,json=historyKey,proto3" json:"history_key,omitempty"`
	// The session's resumed Revision, without bundle. A final commit equal to its final commit is
	// reported as RevisionUnchanged.
	PriorRevision *PriorRevision `protobuf:"bytes,7,opt,name=prior_revision,json=priorRevision,proto3" json:"prior_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRevisionSpec) Reset() {
	*x = DeliverRevisionSpec{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRevisionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRevisionSpec) ProtoMessage() {}

func (x *DeliverRevisionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRevisionSpec.ProtoReflect.Descriptor instead.
func (*DeliverRevisionSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{7}
}

func (x *DeliverRevisionSpec) GetSessionExecutionId() string {
	if x != nil {
		return x.SessionExecutionId
	}
	return ""
}

func (x *DeliverRevisionSpec) GetCheckoutExecutionId() string {
	if x != nil {
		return x.CheckoutExecutionId
	}
	return ""
}

func (x *DeliverRevisionSpec) GetBaseCommit() string {
	if x != nil {
		return x.BaseCommit
	}
	return ""
}

func (x *DeliverRevisionSpec) GetRevisionRef() string {
	if x != nil {
		return x.RevisionRef
	}
	return ""
}

func (x *DeliverRevisionSpec) GetBundleKey() string {
	if x != nil {
		return x.BundleKey
	}
	return ""
}

func (x *DeliverRevisionSpec) GetHistoryKey() string {
	if x != nil {
		return x.HistoryKey
	}
	return ""
}

func (x *DeliverRevisionSpec) GetPriorRevision() *PriorRevision {
	if x != nil {
		return x.PriorRevision
	}
	return nil
}

// An object the Node uploaded, as the Node measured it; Cloud verifies it before registering.
type StoredObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size  uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Lowercase hexadecimal SHA-256.
	Sha256        string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredObject) Reset() {
	*x = StoredObject{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredObject) ProtoMessage() {}

func (x *StoredObject) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredObject.ProtoReflect.Descriptor instead.
func (*StoredObject) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{8}
}

func (x *StoredObject) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoredObject) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoredObject) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type RevisionDelivered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalCommit   string                 `protobuf:"bytes,1,opt,name=final_commit,json=finalCommit,proto3" json:"final_commit,omitempty"`
	BaseCommit    string                 `protobuf:"bytes,2,opt,name=base_commit,json=baseCommit,proto3" json:"base_commit,omitempty"`
	RevisionRef   string                 `protobuf:"bytes,3,opt,name=revision_ref,json=revisionRef,proto3" json:"revision_ref,omitempty"`
	Bundle        *StoredObject          `protobuf:"bytes,4,opt,name=bundle,proto3" json:"bundle,omitempty"`
	History       *StoredObject          `protobuf:"bytes,5,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionDelivered) Reset() {
	*x = RevisionDelivered{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionDelivered) ProtoMessage() {}

func (x *RevisionDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionDelivered.ProtoReflect.Descriptor instead.
func (*RevisionDelivered) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{9}
}

func (x *RevisionDelivered) GetFinalCommit() string {
	if x != nil {
		return x.FinalCommit
	}
	return ""
}

func (x *RevisionDelivered) GetBaseCommit() string {
	if x != nil {
		return x.BaseCommit
	}
	return ""
}

func (x *RevisionDelivered) GetRevisionRef() string {
	if x != nil {
		return x.RevisionRef
	}
	return ""
}

func (x *RevisionDelivered) GetBundle() *StoredObject {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *RevisionDelivered) GetHistory() *StoredObject {
	if x != nil {
		return x.History
	}
	return nil
}

// The final commit equals the base commit, or the delivery spec's prior_revision final commit (a
// resumed run that added nothing): no bundle, only the session history.
type RevisionUnchanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalCommit   string                 `protobuf:"bytes,1,opt,name=final_commit,json=finalCommit,proto3" json:"final_commit,omitempty"`
	BaseCommit    string                 `protobuf:"bytes,2,opt,name=base_commit,json=baseCommit,proto3" json:"base_commit,omitempty"`
	RevisionRef   string                 `protobuf:"bytes,3,opt,name=revision_ref,json=revisionRef,proto3" json:"revision_ref,omitempty"`
	History       *StoredObject          `protobuf:"bytes,4,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionUnchanged) Reset() {
	*x = RevisionUnchanged{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionUnchanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionUnchanged) ProtoMessage() {}

func (x *RevisionUnchanged) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionUnchanged.ProtoReflect.Descriptor instead.
func (*RevisionUnchanged) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{10}
}

func (x *RevisionUnchanged) GetFinalCommit() string {
	if x != nil {
		return x.FinalCommit
	}
	return ""
}

func (x *RevisionUnchanged) GetBaseCommit() string {
	if x != nil {
		return x.BaseCommit
	}
	return ""
}

func (x *RevisionUnchanged) GetRevisionRef() string {
	if x != nil {
		return x.RevisionRef
	}
	return ""
}

func (x *RevisionUnchanged) GetHistory() *StoredObject {
	if x != nil {
		return x.History
	}
	return nil
}

type RevisionFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        RevisionFailureReason  `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.RevisionFailureReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionFailed) Reset() {
	*x = RevisionFailed{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionFailed) ProtoMessage() {}

func (x *RevisionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionFailed.ProtoReflect.Descriptor instead.
func (*RevisionFailed) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{11}
}

func (x *RevisionFailed) GetReason() RevisionFailureReason {
	if x != nil {
		return x.Reason
	}
	return RevisionFailureReason_REVISION_FAILURE_REASON_UNSPECIFIED
}

// A presigned single-object upload. It is a short-lived bearer credential: Cloud, the Controller
// and the Node keep it in memory only and never log it.
type UploadGrant struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Always PUT in the first version.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Headers the upload must carry unchanged, including signed `If-None-Match: *` (create only).
	// A checksum-bound grant includes `x-amz-checksum-sha256`; legacy uploaders add that digest.
	// On 412, preserve the existing object and submit the declaration for Cloud verification;
	// neither the uploader nor Controller may treat 412 alone as proof that its bytes match.
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadGrant) Reset() {
	*x = UploadGrant{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGrant) ProtoMessage() {}

func (x *UploadGrant) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGrant.ProtoReflect.Descriptor instead.
func (*UploadGrant) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{12}
}

func (x *UploadGrant) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadGrant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadGrant) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UploadGrant) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *UploadGrant) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// A presigned single-object read of a prior Revision's bundle. Like UploadGrant it is a short-lived
// bearer credential kept in memory only and never logged.
type DownloadGrant struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Url       string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Always GET.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Headers the download must carry unchanged.
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadGrant) Reset() {
	*x = DownloadGrant{}
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadGrant) ProtoMessage() {}

func (x *DownloadGrant) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadGrant.ProtoReflect.Descriptor instead.
func (*DownloadGrant) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadGrant) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DownloadGrant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadGrant) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DownloadGrant) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DownloadGrant) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_ora_cloud_internal_v1_agent_executions_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_agent_executions_proto_rawDesc = "" +
	"\n" +
	",ora/cloud/internal/v1/agent_executions.proto\x12\x15ora.cloud.internal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\vGitIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"Q\n" +
	"\fContentBlock\x128\n" +
	"\x04text\x18\x01 \x01(\v2\".ora.cloud.internal.v1.TextContentH\x00R\x04textB\a\n" +
	"\x05block\"b\n" +
	"\bUserTurn\x12\x17\n" +
	"\aturn_id\x18\x01 \x01(\tR\x06turnId\x12=\n" +
	"\acontent\x18\x02 \x03(\v2#.ora.cloud.internal.v1.ContentBlockR\acontent\"\x90\x01\n" +
	"\rPriorRevision\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12!\n" +
	"\ffinal_commit\x18\x02 \x01(\tR\vfinalCommit\x12;\n" +
	"\x06bundle\x18\x03 \x01(\v2#.ora.cloud.internal.v1.StoredObjectR\x06bundle\"\xf8\x02\n" +
	"\x10AgentSessionSpec\x12&\n" +
	"\x0fagent_plugin_id\x18\x01 \x01(\tR\ragentPluginId\x120\n" +
	"\x14agent_plugin_version\x18\x02 \x01(\tR\x12agentPluginVersion\x122\n" +
	"\x15checkout_execution_id\x18\x03 \x01(\tR\x13checkoutExecutionId\x12E\n" +
	"\fgit_identity\x18\x04 \x01(\v2\".ora.cloud.internal.v1.GitIdentityR\vgitIdentity\x12B\n" +
	"\finitial_turn\x18\x05 \x01(\v2\x1f.ora.cloud.internal.v1.UserTurnR\vinitialTurn\x12K\n" +
	"\x0eprior_revision\x18\x06 \x01(\v2$.ora.cloud.internal.v1.PriorRevisionR\rpriorRevision\"\x81\x01\n" +
	"\x11AgentSessionEnded\x12D\n" +
	"\x06reason\x18\x01 \x01(\x0e2,.ora.cloud.internal.v1.AgentSessionEndReasonR\x06reason\x12\x1b\n" +
	"\x06detail\x18\x02 \x01(\tH\x00R\x06detail\x88\x01\x01B\t\n" +
	"\a_detail\"\xcc\x02\n" +
	"\x13DeliverRevisionSpec\x120\n" +
	"\x14session_execution_id\x18\x01 \x01(\tR\x12sessionExecutionId\x122\n" +
	"\x15checkout_execution_id\x18\x02 \x01(\tR\x13checkoutExecutionId\x12\x1f\n" +
	"\vbase_commit\x18\x03 \x01(\tR\n" +
	"baseCommit\x12!\n" +
	"\frevision_ref\x18\x04 \x01(\tR\vrevisionRef\x12\x1d\n" +
	"\n" +
	"bundle_key\x18\x05 \x01(\tR\tbundleKey\x12\x1f\n" +
	"\vhistory_key\x18\x06 \x01(\tR\n" +
	"historyKey\x12K\n" +
	"\x0eprior_revision\x18\a \x01(\v2$.ora.cloud.internal.v1.PriorRevisionR\rpriorRevision\"L\n" +
	"\fStoredObject\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"\xf6\x01\n" +
	"\x11RevisionDelivered\x12!\n" +
	"\ffinal_commit\x18\x01 \x01(\tR\vfinalCommit\x12\x1f\n" +
	"\vbase_commit\x18\x02 \x01(\tR\n" +
	"baseCommit\x12!\n" +
	"\frevision_ref\x18\x03 \x01(\tR\vrevisionRef\x12;\n" +
	"\x06bundle\x18\x04 \x01(\v2#.ora.cloud.internal.v1.StoredObjectR\x06bundle\x12=\n" +
	"\ahistory\x18\x05 \x01(\v2#.ora.cloud.internal.v1.StoredObjectR\ahistory\"\xb9\x01\n" +
	"\x11RevisionUnchanged\x12!\n" +
	"\ffinal_commit\x18\x01 \x01(\tR\vfinalCommit\x12\x1f\n" +
	"\vbase_commit\x18\x02 \x01(\tR\n" +
	"baseCommit\x12!\n" +
	"\frevision_ref\x18\x03 \x01(\tR\vrevisionRef\x12=\n" +
	"\ahistory\x18\x04 \x01(\v2#.ora.cloud.internal.v1.StoredObjectR\ahistory\"V\n" +
	"\x0eRevisionFailed\x12D\n" +
	"\x06reason\x18\x01 \x01(\x0e2,.ora.cloud.internal.v1.RevisionFailureReasonR\x06reason\"\x98\x02\n" +
	"\vUploadGrant\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12I\n" +
	"\aheaders\x18\x04 \x03(\v2/.ora.cloud.internal.v1.UploadGrant.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\rDownloadGrant\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12K\n" +
	"\aheaders\x18\x04 \x03(\v21.ora.cloud.internal.v1.DownloadGrant.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x92\x02\n" +
	"\x15AgentSessionEndReason\x12(\n" +
	"$AGENT_SESSION_END_REASON_UNSPECIFIED\x10\x00\x12'\n" +
	"#AGENT_SESSION_END_REASON_USER_ENDED\x10\x01\x12)\n" +
	"%AGENT_SESSION_END_REASON_IDLE_TIMEOUT\x10\x02\x12&\n" +
	"\"AGENT_SESSION_END_REASON_CANCELLED\x10\x03\x12)\n" +
	"%AGENT_SESSION_END_REASON_AGENT_FAILED\x10\x04\x12(\n" +
	"$AGENT_SESSION_END_REASON_INTERRUPTED\x10\x05*\x88\x03\n" +
	"\x15RevisionFailureReason\x12'\n" +
	"#REVISION_FAILURE_REASON_UNSPECIFIED\x10\x00\x12/\n" +
	"+REVISION_FAILURE_REASON_SESSION_NOT_SETTLED\x10\x01\x120\n" +
	",REVISION_FAILURE_REASON_CHECKOUT_UNAVAILABLE\x10\x02\x12+\n" +
	"'REVISION_FAILURE_REASON_SNAPSHOT_FAILED\x10\x03\x12)\n" +
	"%REVISION_FAILURE_REASON_BUNDLE_FAILED\x10\x04\x12/\n" +
	"+REVISION_FAILURE_REASON_HISTORY_UNAVAILABLE\x10\x05\x12)\n" +
	"%REVISION_FAILURE_REASON_UPLOAD_FAILED\x10\x06\x12/\n" +
	"+REVISION_FAILURE_REASON_VERIFICATION_FAILED\x10\aB\xe5\x01\n" +
	"\x19com.ora.cloud.internal.v1B\x14AgentExecutionsProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_agent_executions_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_agent_executions_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_agent_executions_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_agent_executions_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_agent_executions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_agent_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_agent_executions_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_agent_executions_proto_rawDescData
}

var file_ora_cloud_internal_v1_agent_executions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ora_cloud_internal_v1_agent_executions_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_ora_cloud_internal_v1_agent_executions_proto_goTypes = []any{
	(AgentSessionEndReason)(0),    // 0: ora.cloud.internal.v1.AgentSessionEndReason
	(RevisionFailureReason)(0),    // 1: ora.cloud.internal.v1.RevisionFailureReason
	(*GitIdentity)(nil),           // 2: ora.cloud.internal.v1.GitIdentity
	(*TextContent)(nil),           // 3: ora.cloud.internal.v1.TextContent
	(*ContentBlock)(nil),          // 4: ora.cloud.internal.v1.ContentBlock
	(*UserTurn)(nil),              // 5: ora.cloud.internal.v1.UserTurn
	(*PriorRevision)(nil),         // 6: ora.cloud.internal.v1.PriorRevision
	(*AgentSessionSpec)(nil),      // 7: ora.cloud.internal.v1.AgentSessionSpec
	(*AgentSessionEnded)(nil),     // 8: ora.cloud.internal.v1.AgentSessionEnded
	(*DeliverRevisionSpec)(nil),   // 9: ora.cloud.internal.v1.DeliverRevisionSpec
	(*StoredObject)(nil),          // 10: ora.cloud.internal.v1.StoredObject
	(*RevisionDelivered)(nil),     // 11: ora.cloud.internal.v1.RevisionDelivered
	(*RevisionUnchanged)(nil),     // 12: ora.cloud.internal.v1.RevisionUnchanged
	(*RevisionFailed)(nil),        // 13: ora.cloud.internal.v1.RevisionFailed
	(*UploadGrant)(nil),           // 14: ora.cloud.internal.v1.UploadGrant
	(*DownloadGrant)(nil),         // 15: ora.cloud.internal.v1.DownloadGrant
	nil,                           // 16: ora.cloud.internal.v1.UploadGrant.HeadersEntry
	nil,                           // 17: ora.cloud.internal.v1.DownloadGrant.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_ora_cloud_internal_v1_agent_executions_proto_depIdxs = []int32{
	3,  // 0: ora.cloud.internal.v1.ContentBlock.text:type_name -> ora.cloud.internal.v1.TextContent
	4,  // 1: ora.cloud.internal.v1.UserTurn.content:type_name -> ora.cloud.internal.v1.ContentBlock
	10, // 2: ora.cloud.internal.v1.PriorRevision.bundle:type_name -> ora.cloud.internal.v1.StoredObject
	2,  // 3: ora.cloud.internal.v1.AgentSessionSpec.git_identity:type_name -> ora.cloud.internal.v1.GitIdentity
	5,  // 4: ora.cloud.internal.v1.AgentSessionSpec.initial_turn:type_name -> ora.cloud.internal.v1.UserTurn
	6,  // 5: ora.cloud.internal.v1.AgentSessionSpec.prior_revision:type_name -> ora.cloud.internal.v1.PriorRevision
	0,  // 6: ora.cloud.internal.v1.AgentSessionEnded.reason:type_name -> ora.cloud.internal.v1.AgentSessionEndReason
	6,  // 7: ora.cloud.internal.v1.DeliverRevisionSpec.prior_revision:type_name -> ora.cloud.internal.v1.PriorRevision
	10, // 8: ora.cloud.internal.v1.RevisionDelivered.bundle:type_name -> ora.cloud.internal.v1.StoredObject
	10, // 9: ora.cloud.internal.v1.RevisionDelivered.history:type_name -> ora.cloud.internal.v1.StoredObject
	10, // 10: ora.cloud.internal.v1.RevisionUnchanged.history:type_name -> ora.cloud.internal.v1.StoredObject
	1,  // 11: ora.cloud.internal.v1.RevisionFailed.reason:type_name -> ora.cloud.internal.v1.RevisionFailureReason
	16, // 12: ora.cloud.internal.v1.UploadGrant.headers:type_name -> ora.cloud.internal.v1.UploadGrant.HeadersEntry
	18, // 13: ora.cloud.internal.v1.UploadGrant.expires_at:type_name -> google.protobuf.Timestamp
	17, // 14: ora.cloud.internal.v1.DownloadGrant.headers:type_name -> ora.cloud.internal.v1.DownloadGrant.HeadersEntry
	18, // 15: ora.cloud.internal.v1.DownloadGrant.expires_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_agent_executions_proto_init() }
func file_ora_cloud_internal_v1_agent_executions_proto_init() {
	if File_ora_cloud_internal_v1_agent_executions_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[2].OneofWrappers = []any{
		(*ContentBlock_Text)(nil),
	}
	file_ora_cloud_internal_v1_agent_executions_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_agent_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_agent_executions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ora_cloud_internal_v1_agent_executions_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_agent_executions_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_agent_executions_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_agent_executions_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_agent_executions_proto = out.File
	file_ora_cloud_internal_v1_agent_executions_proto_goTypes = nil
	file_ora_cloud_internal_v1_agent_executions_proto_depIdxs = nil
}
