// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/nodes.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeReportService_RegisterNode_FullMethodName     = "/ora.cloud.internal.v1.NodeReportService/RegisterNode"
	NodeReportService_ReportNodeStatus_FullMethodName = "/ora.cloud.internal.v1.NodeReportService/ReportNodeStatus"
	NodeReportService_EndNode_FullMethodName          = "/ora.cloud.internal.v1.NodeReportService/EndNode"
	NodeReportService_ReportNodeIdle_FullMethodName   = "/ora.cloud.internal.v1.NodeReportService/ReportNodeIdle"
)

// NodeReportServiceClient is the client API for NodeReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Node reports made by the lease-holding Controller on behalf of the desktop Nodes it holds a
// session with. A Node never talks to Cloud and holds no Cloud credential; the Controller's own
// observation of the handshake and the session is the node-step evidence. Every call is fenced by
// `epoch` and carries a `submission_id` with the same replay rules as ExecutionService, and every
// report is refused (FAILED_PRECONDITION or ABORTED) unless its sandbox is the Workspace's current
// generation and has not been terminated.
type NodeReportServiceClient interface {
	// Registers one Node incarnation after its handshake completed. Idempotent by
	// (sandbox_instance_id, node.node_incarnation_id). node.node_id must equal the NodeId the sandbox's
	// ensure effect reported; a second incarnation of the same sandbox fails with ABORTED (CONFLICT)
	// until the first one was ended.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Reports the session state and refreshes the heartbeat. The Controller reports at most every
	// 10 seconds while the session lasts; Cloud treats a Node silent for 30 seconds as not ready.
	ReportNodeStatus(ctx context.Context, in *ReportNodeStatusRequest, opts ...grpc.CallOption) (*ReportNodeStatusResponse, error)
	// Ends one incarnation, for example when the Node reconnected as a new incarnation. Ending an
	// already ended incarnation returns it unchanged.
	EndNode(ctx context.Context, in *EndNodeRequest, opts ...grpc.CallOption) (*EndNodeResponse, error)
	// Reports whether the Node is idle for one quiesce request. idle may be true only when the
	// Controller has no dispatch to this Node without a terminal result, and has stopped dispatching
	// to it; false restores admission and fails the requesting operation.
	ReportNodeIdle(ctx context.Context, in *ReportNodeIdleRequest, opts ...grpc.CallOption) (*ReportNodeIdleResponse, error)
}

type nodeReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeReportServiceClient(cc grpc.ClientConnInterface) NodeReportServiceClient {
	return &nodeReportServiceClient{cc}
}

func (c *nodeReportServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeReportService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeReportServiceClient) ReportNodeStatus(ctx context.Context, in *ReportNodeStatusRequest, opts ...grpc.CallOption) (*ReportNodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportNodeStatusResponse)
	err := c.cc.Invoke(ctx, NodeReportService_ReportNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeReportServiceClient) EndNode(ctx context.Context, in *EndNodeRequest, opts ...grpc.CallOption) (*EndNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndNodeResponse)
	err := c.cc.Invoke(ctx, NodeReportService_EndNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeReportServiceClient) ReportNodeIdle(ctx context.Context, in *ReportNodeIdleRequest, opts ...grpc.CallOption) (*ReportNodeIdleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportNodeIdleResponse)
	err := c.cc.Invoke(ctx, NodeReportService_ReportNodeIdle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeReportServiceServer is the server API for NodeReportService service.
// All implementations must embed UnimplementedNodeReportServiceServer
// for forward compatibility.
//
// Node reports made by the lease-holding Controller on behalf of the desktop Nodes it holds a
// session with. A Node never talks to Cloud and holds no Cloud credential; the Controller's own
// observation of the handshake and the session is the node-step evidence. Every call is fenced by
// `epoch` and carries a `submission_id` with the same replay rules as ExecutionService, and every
// report is refused (FAILED_PRECONDITION or ABORTED) unless its sandbox is the Workspace's current
// generation and has not been terminated.
type NodeReportServiceServer interface {
	// Registers one Node incarnation after its handshake completed. Idempotent by
	// (sandbox_instance_id, node.node_incarnation_id). node.node_id must equal the NodeId the sandbox's
	// ensure effect reported; a second incarnation of the same sandbox fails with ABORTED (CONFLICT)
	// until the first one was ended.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Reports the session state and refreshes the heartbeat. The Controller reports at most every
	// 10 seconds while the session lasts; Cloud treats a Node silent for 30 seconds as not ready.
	ReportNodeStatus(context.Context, *ReportNodeStatusRequest) (*ReportNodeStatusResponse, error)
	// Ends one incarnation, for example when the Node reconnected as a new incarnation. Ending an
	// already ended incarnation returns it unchanged.
	EndNode(context.Context, *EndNodeRequest) (*EndNodeResponse, error)
	// Reports whether the Node is idle for one quiesce request. idle may be true only when the
	// Controller has no dispatch to this Node without a terminal result, and has stopped dispatching
	// to it; false restores admission and fails the requesting operation.
	ReportNodeIdle(context.Context, *ReportNodeIdleRequest) (*ReportNodeIdleResponse, error)
	mustEmbedUnimplementedNodeReportServiceServer()
}

// UnimplementedNodeReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeReportServiceServer struct{}

func (UnimplementedNodeReportServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeReportServiceServer) ReportNodeStatus(context.Context, *ReportNodeStatusRequest) (*ReportNodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportNodeStatus not implemented")
}
func (UnimplementedNodeReportServiceServer) EndNode(context.Context, *EndNodeRequest) (*EndNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndNode not implemented")
}
func (UnimplementedNodeReportServiceServer) ReportNodeIdle(context.Context, *ReportNodeIdleRequest) (*ReportNodeIdleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportNodeIdle not implemented")
}
func (UnimplementedNodeReportServiceServer) mustEmbedUnimplementedNodeReportServiceServer() {}
func (UnimplementedNodeReportServiceServer) testEmbeddedByValue()                           {}

// UnsafeNodeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeReportServiceServer will
// result in compilation errors.
type UnsafeNodeReportServiceServer interface {
	mustEmbedUnimplementedNodeReportServiceServer()
}

func RegisterNodeReportServiceServer(s grpc.ServiceRegistrar, srv NodeReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeReportService_ServiceDesc, srv)
}

func _NodeReportService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReportServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeReportService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReportServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeReportService_ReportNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportNodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReportServiceServer).ReportNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeReportService_ReportNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReportServiceServer).ReportNodeStatus(ctx, req.(*ReportNodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeReportService_EndNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReportServiceServer).EndNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeReportService_EndNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReportServiceServer).EndNode(ctx, req.(*EndNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeReportService_ReportNodeIdle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportNodeIdleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReportServiceServer).ReportNodeIdle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeReportService_ReportNodeIdle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReportServiceServer).ReportNodeIdle(ctx, req.(*ReportNodeIdleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeReportService_ServiceDesc is the grpc.ServiceDesc for NodeReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.NodeReportService",
	HandlerType: (*NodeReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeReportService_RegisterNode_Handler,
		},
		{
			MethodName: "ReportNodeStatus",
			Handler:    _NodeReportService_ReportNodeStatus_Handler,
		},
		{
			MethodName: "EndNode",
			Handler:    _NodeReportService_EndNode_Handler,
		},
		{
			MethodName: "ReportNodeIdle",
			Handler:    _NodeReportService_ReportNodeIdle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/nodes.proto",
}
