// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/nodes.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeConnection int32

const (
	NodeConnection_NODE_CONNECTION_UNSPECIFIED  NodeConnection = 0
	NodeConnection_NODE_CONNECTION_CONNECTED    NodeConnection = 1
	NodeConnection_NODE_CONNECTION_DISCONNECTED NodeConnection = 2
	// Set by Cloud only: the incarnation ended or its sandbox was terminated.
	NodeConnection_NODE_CONNECTION_ENDED NodeConnection = 3
)

// Enum value maps for NodeConnection.
var (
	NodeConnection_name = map[int32]string{
		0: "NODE_CONNECTION_UNSPECIFIED",
		1: "NODE_CONNECTION_CONNECTED",
		2: "NODE_CONNECTION_DISCONNECTED",
		3: "NODE_CONNECTION_ENDED",
	}
	NodeConnection_value = map[string]int32{
		"NODE_CONNECTION_UNSPECIFIED":  0,
		"NODE_CONNECTION_CONNECTED":    1,
		"NODE_CONNECTION_DISCONNECTED": 2,
		"NODE_CONNECTION_ENDED":        3,
	}
)

func (x NodeConnection) Enum() *NodeConnection {
	p := new(NodeConnection)
	*p = x
	return p
}

func (x NodeConnection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeConnection) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_nodes_proto_enumTypes[0].Descriptor()
}

func (NodeConnection) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_nodes_proto_enumTypes[0]
}

func (x NodeConnection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeConnection.Descriptor instead.
func (NodeConnection) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{0}
}

// Cloud's record of one Node incarnation.
type NodeRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cloud's own identity of this incarnation record; later reports name it.
	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SandboxInstanceId string `protobuf:"bytes,2,opt,name=sandbox_instance_id,json=sandboxInstanceId,proto3" json:"sandbox_instance_id,omitempty"`
	WorkspaceId       string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Unset only for records a Node registered itself before Controllers reported Nodes.
	Identity    *NodeIdentity  `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Connection  NodeConnection `protobuf:"varint,5,opt,name=connection,proto3,enum=ora.cloud.internal.v1.NodeConnection" json:"connection,omitempty"`
	Initialized bool           `protobuf:"varint,6,opt,name=initialized,proto3" json:"initialized,omitempty"`
	// Resource version; every report names the version it was based on.
	Version int64 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	// Admission epoch of the latest accepted idle evidence.
	IdleAdmissionEpoch *int64 `protobuf:"varint,8,opt,name=idle_admission_epoch,json=idleAdmissionEpoch,proto3,oneof" json:"idle_admission_epoch,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeRecord) Reset() {
	*x = NodeRecord{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRecord) ProtoMessage() {}

func (x *NodeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRecord.ProtoReflect.Descriptor instead.
func (*NodeRecord) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeRecord) GetSandboxInstanceId() string {
	if x != nil {
		return x.SandboxInstanceId
	}
	return ""
}

func (x *NodeRecord) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *NodeRecord) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *NodeRecord) GetConnection() NodeConnection {
	if x != nil {
		return x.Connection
	}
	return NodeConnection_NODE_CONNECTION_UNSPECIFIED
}

func (x *NodeRecord) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *NodeRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeRecord) GetIdleAdmissionEpoch() int64 {
	if x != nil && x.IdleAdmissionEpoch != nil {
		return *x.IdleAdmissionEpoch
	}
	return 0
}

type RegisterNodeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch        int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The effect ID of the sandbox's ensure effect, which is also the sandbox instance ID.
	SandboxInstanceId string        `protobuf:"bytes,3,opt,name=sandbox_instance_id,json=sandboxInstanceId,proto3" json:"sandbox_instance_id,omitempty"`
	Generation        int64         `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Node              *NodeIdentity `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	ProtocolVersion   uint32        `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RegisterNodeRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RegisterNodeRequest) GetSandboxInstanceId() string {
	if x != nil {
		return x.SandboxInstanceId
	}
	return ""
}

func (x *RegisterNodeRequest) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RegisterNodeRequest) GetNode() *NodeIdentity {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RegisterNodeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeRecord            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetNode() *NodeRecord {
	if x != nil {
		return x.Node
	}
	return nil
}

type ReportNodeStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch          int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NodeInstanceId string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	Version        int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// CONNECTED or DISCONNECTED.
	Connection    NodeConnection `protobuf:"varint,5,opt,name=connection,proto3,enum=ora.cloud.internal.v1.NodeConnection" json:"connection,omitempty"`
	Initialized   bool           `protobuf:"varint,6,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeStatusRequest) Reset() {
	*x = ReportNodeStatusRequest{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeStatusRequest) ProtoMessage() {}

func (x *ReportNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{3}
}

func (x *ReportNodeStatusRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ReportNodeStatusRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ReportNodeStatusRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *ReportNodeStatusRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReportNodeStatusRequest) GetConnection() NodeConnection {
	if x != nil {
		return x.Connection
	}
	return NodeConnection_NODE_CONNECTION_UNSPECIFIED
}

func (x *ReportNodeStatusRequest) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type ReportNodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeRecord            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeStatusResponse) Reset() {
	*x = ReportNodeStatusResponse{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeStatusResponse) ProtoMessage() {}

func (x *ReportNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{4}
}

func (x *ReportNodeStatusResponse) GetNode() *NodeRecord {
	if x != nil {
		return x.Node
	}
	return nil
}

type EndNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch          int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NodeInstanceId string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	Version        int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EndNodeRequest) Reset() {
	*x = EndNodeRequest{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndNodeRequest) ProtoMessage() {}

func (x *EndNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndNodeRequest.ProtoReflect.Descriptor instead.
func (*EndNodeRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{5}
}

func (x *EndNodeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *EndNodeRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EndNodeRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *EndNodeRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EndNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeRecord            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndNodeResponse) Reset() {
	*x = EndNodeResponse{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndNodeResponse) ProtoMessage() {}

func (x *EndNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndNodeResponse.ProtoReflect.Descriptor instead.
func (*EndNodeResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{6}
}

func (x *EndNodeResponse) GetNode() *NodeRecord {
	if x != nil {
		return x.Node
	}
	return nil
}

type ReportNodeIdleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch          int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NodeInstanceId string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	Version        int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	OperationId    string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	AdmissionEpoch int64                  `protobuf:"varint,6,opt,name=admission_epoch,json=admissionEpoch,proto3" json:"admission_epoch,omitempty"`
	Idle           bool                   `protobuf:"varint,7,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportNodeIdleRequest) Reset() {
	*x = ReportNodeIdleRequest{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeIdleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeIdleRequest) ProtoMessage() {}

func (x *ReportNodeIdleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeIdleRequest.ProtoReflect.Descriptor instead.
func (*ReportNodeIdleRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{7}
}

func (x *ReportNodeIdleRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *ReportNodeIdleRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ReportNodeIdleRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *ReportNodeIdleRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReportNodeIdleRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReportNodeIdleRequest) GetAdmissionEpoch() int64 {
	if x != nil {
		return x.AdmissionEpoch
	}
	return 0
}

func (x *ReportNodeIdleRequest) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

type ReportNodeIdleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when idle was false: Cloud restored admission and failed the operation.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// The updated record when the idle evidence was accepted.
	Node          *NodeRecord `protobuf:"bytes,2,opt,name=node,proto3,oneof" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeIdleResponse) Reset() {
	*x = ReportNodeIdleResponse{}
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeIdleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeIdleResponse) ProtoMessage() {}

func (x *ReportNodeIdleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_nodes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeIdleResponse.ProtoReflect.Descriptor instead.
func (*ReportNodeIdleResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP(), []int{8}
}

func (x *ReportNodeIdleResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportNodeIdleResponse) GetNode() *NodeRecord {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_ora_cloud_internal_v1_nodes_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_nodes_proto_rawDesc = "" +
	"\n" +
	"!ora/cloud/internal/v1/nodes.proto\x12\x15ora.cloud.internal.v1\x1a&ora/cloud/internal/v1/executions.proto\"\x83\x03\n" +
	"\n" +
	"NodeRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13sandbox_instance_id\x18\x02 \x01(\tR\x11sandboxInstanceId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12?\n" +
	"\bidentity\x18\x04 \x01(\v2#.ora.cloud.internal.v1.NodeIdentityR\bidentity\x12E\n" +
	"\n" +
	"connection\x18\x05 \x01(\x0e2%.ora.cloud.internal.v1.NodeConnectionR\n" +
	"connection\x12 \n" +
	"\vinitialized\x18\x06 \x01(\bR\vinitialized\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x125\n" +
	"\x14idle_admission_epoch\x18\b \x01(\x03H\x00R\x12idleAdmissionEpoch\x88\x01\x01B\x17\n" +
	"\x15_idle_admission_epoch\"\x84\x02\n" +
	"\x13RegisterNodeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12.\n" +
	"\x13sandbox_instance_id\x18\x03 \x01(\tR\x11sandboxInstanceId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x03R\n" +
	"generation\x127\n" +
	"\x04node\x18\x05 \x01(\v2#.ora.cloud.internal.v1.NodeIdentityR\x04node\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\rR\x0fprotocolVersion\"M\n" +
	"\x14RegisterNodeResponse\x125\n" +
	"\x04node\x18\x01 \x01(\v2!.ora.cloud.internal.v1.NodeRecordR\x04node\"\x81\x02\n" +
	"\x17ReportNodeStatusRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12E\n" +
	"\n" +
	"connection\x18\x05 \x01(\x0e2%.ora.cloud.internal.v1.NodeConnectionR\n" +
	"connection\x12 \n" +
	"\vinitialized\x18\x06 \x01(\bR\vinitialized\"Q\n" +
	"\x18ReportNodeStatusResponse\x125\n" +
	"\x04node\x18\x01 \x01(\v2!.ora.cloud.internal.v1.NodeRecordR\x04node\"\x8f\x01\n" +
	"\x0eEndNodeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"H\n" +
	"\x0fEndNodeResponse\x125\n" +
	"\x04node\x18\x01 \x01(\v2!.ora.cloud.internal.v1.NodeRecordR\x04node\"\xf6\x01\n" +
	"\x15ReportNodeIdleRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\x12'\n" +
	"\x0fadmission_epoch\x18\x06 \x01(\x03R\x0eadmissionEpoch\x12\x12\n" +
	"\x04idle\x18\a \x01(\bR\x04idle\"y\n" +
	"\x16ReportNodeIdleResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12:\n" +
	"\x04node\x18\x02 \x01(\v2!.ora.cloud.internal.v1.NodeRecordH\x00R\x04node\x88\x01\x01B\a\n" +
	"\x05_node*\x8d\x01\n" +
	"\x0eNodeConnection\x12\x1f\n" +
	"\x1bNODE_CONNECTION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NODE_CONNECTION_CONNECTED\x10\x01\x12 \n" +
	"\x1cNODE_CONNECTION_DISCONNECTED\x10\x02\x12\x19\n" +
	"\x15NODE_CONNECTION_ENDED\x10\x032\xba\x03\n" +
	"\x11NodeReportService\x12g\n" +
	"\fRegisterNode\x12*.ora.cloud.internal.v1.RegisterNodeRequest\x1a+.ora.cloud.internal.v1.RegisterNodeResponse\x12s\n" +
	"\x10ReportNodeStatus\x12..ora.cloud.internal.v1.ReportNodeStatusRequest\x1a/.ora.cloud.internal.v1.ReportNodeStatusResponse\x12X\n" +
	"\aEndNode\x12%.ora.cloud.internal.v1.EndNodeRequest\x1a&.ora.cloud.internal.v1.EndNodeResponse\x12m\n" +
	"\x0eReportNodeIdle\x12,.ora.cloud.internal.v1.ReportNodeIdleRequest\x1a-.ora.cloud.internal.v1.ReportNodeIdleResponseB\xdb\x01\n" +
	"\x19com.ora.cloud.internal.v1B\n" +
	"NodesProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_nodes_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_nodes_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_nodes_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_nodes_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_nodes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_nodes_proto_rawDesc), len(file_ora_cloud_internal_v1_nodes_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_nodes_proto_rawDescData
}

var file_ora_cloud_internal_v1_nodes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ora_cloud_internal_v1_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ora_cloud_internal_v1_nodes_proto_goTypes = []any{
	(NodeConnection)(0),              // 0: ora.cloud.internal.v1.NodeConnection
	(*NodeRecord)(nil),               // 1: ora.cloud.internal.v1.NodeRecord
	(*RegisterNodeRequest)(nil),      // 2: ora.cloud.internal.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 3: ora.cloud.internal.v1.RegisterNodeResponse
	(*ReportNodeStatusRequest)(nil),  // 4: ora.cloud.internal.v1.ReportNodeStatusRequest
	(*ReportNodeStatusResponse)(nil), // 5: ora.cloud.internal.v1.ReportNodeStatusResponse
	(*EndNodeRequest)(nil),           // 6: ora.cloud.internal.v1.EndNodeRequest
	(*EndNodeResponse)(nil),          // 7: ora.cloud.internal.v1.EndNodeResponse
	(*ReportNodeIdleRequest)(nil),    // 8: ora.cloud.internal.v1.ReportNodeIdleRequest
	(*ReportNodeIdleResponse)(nil),   // 9: ora.cloud.internal.v1.ReportNodeIdleResponse
	(*NodeIdentity)(nil),             // 10: ora.cloud.internal.v1.NodeIdentity
}
var file_ora_cloud_internal_v1_nodes_proto_depIdxs = []int32{
	10, // 0: ora.cloud.internal.v1.NodeRecord.identity:type_name -> ora.cloud.internal.v1.NodeIdentity
	0,  // 1: ora.cloud.internal.v1.NodeRecord.connection:type_name -> ora.cloud.internal.v1.NodeConnection
	10, // 2: ora.cloud.internal.v1.RegisterNodeRequest.node:type_name -> ora.cloud.internal.v1.NodeIdentity
	1,  // 3: ora.cloud.internal.v1.RegisterNodeResponse.node:type_name -> ora.cloud.internal.v1.NodeRecord
	0,  // 4: ora.cloud.internal.v1.ReportNodeStatusRequest.connection:type_name -> ora.cloud.internal.v1.NodeConnection
	1,  // 5: ora.cloud.internal.v1.ReportNodeStatusResponse.node:type_name -> ora.cloud.internal.v1.NodeRecord
	1,  // 6: ora.cloud.internal.v1.EndNodeResponse.node:type_name -> ora.cloud.internal.v1.NodeRecord
	1,  // 7: ora.cloud.internal.v1.ReportNodeIdleResponse.node:type_name -> ora.cloud.internal.v1.NodeRecord
	2,  // 8: ora.cloud.internal.v1.NodeReportService.RegisterNode:input_type -> ora.cloud.internal.v1.RegisterNodeRequest
	4,  // 9: ora.cloud.internal.v1.NodeReportService.ReportNodeStatus:input_type -> ora.cloud.internal.v1.ReportNodeStatusRequest
	6,  // 10: ora.cloud.internal.v1.NodeReportService.EndNode:input_type -> ora.cloud.internal.v1.EndNodeRequest
	8,  // 11: ora.cloud.internal.v1.NodeReportService.ReportNodeIdle:input_type -> ora.cloud.internal.v1.ReportNodeIdleRequest
	3,  // 12: ora.cloud.internal.v1.NodeReportService.RegisterNode:output_type -> ora.cloud.internal.v1.RegisterNodeResponse
	5,  // 13: ora.cloud.internal.v1.NodeReportService.ReportNodeStatus:output_type -> ora.cloud.internal.v1.ReportNodeStatusResponse
	7,  // 14: ora.cloud.internal.v1.NodeReportService.EndNode:output_type -> ora.cloud.internal.v1.EndNodeResponse
	9,  // 15: ora.cloud.internal.v1.NodeReportService.ReportNodeIdle:output_type -> ora.cloud.internal.v1.ReportNodeIdleResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_nodes_proto_init() }
func file_ora_cloud_internal_v1_nodes_proto_init() {
	if File_ora_cloud_internal_v1_nodes_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_executions_proto_init()
	file_ora_cloud_internal_v1_nodes_proto_msgTypes[0].OneofWrappers = []any{}
	file_ora_cloud_internal_v1_nodes_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_nodes_proto_rawDesc), len(file_ora_cloud_internal_v1_nodes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_nodes_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_nodes_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_nodes_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_nodes_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_nodes_proto = out.File
	file_ora_cloud_internal_v1_nodes_proto_goTypes = nil
	file_ora_cloud_internal_v1_nodes_proto_depIdxs = nil
}
