// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/operations.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceOperationService_ClaimOperation_FullMethodName     = "/ora.cloud.internal.v1.WorkspaceOperationService/ClaimOperation"
	WorkspaceOperationService_PlanEffect_FullMethodName         = "/ora.cloud.internal.v1.WorkspaceOperationService/PlanEffect"
	WorkspaceOperationService_RecordEffectResult_FullMethodName = "/ora.cloud.internal.v1.WorkspaceOperationService/RecordEffectResult"
	WorkspaceOperationService_AdvanceOperation_FullMethodName   = "/ora.cloud.internal.v1.WorkspaceOperationService/AdvanceOperation"
	WorkspaceOperationService_DeferOperation_FullMethodName     = "/ora.cloud.internal.v1.WorkspaceOperationService/DeferOperation"
)

// WorkspaceOperationServiceClient is the client API for WorkspaceOperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runtime Workspace operations driven by the lease-holding Controller: create goes
// sandbox -> node -> clone, start goes sandbox -> node, stop and delete go quiesce -> terminate
// (-> cleanup). Each method runs the same Cloud transaction as the JSON internal API's operation
// actions. Writes are fenced by `epoch` and the operation `version`, and carry a `submission_id`
// with the same replay rules as ExecutionService. The clone step is dispatched and reported through
// ExecutionService with the operation's ID; its input and target Node are decided by Cloud.
type WorkspaceOperationServiceClient interface {
	// Takes the oldest queued, due or running operation for the caller's epoch and returns its
	// snapshot, or none. Calling it again returns the running operation with a new version.
	ClaimOperation(ctx context.Context, in *ClaimOperationRequest, opts ...grpc.CallOption) (*ClaimOperationResponse, error)
	// Records the effect plan of the current step before anything is sent to the Substrate. The
	// effect ID is the Substrate idempotency key; planning the same kind for the same Workspace again
	// returns the original effect.
	PlanEffect(ctx context.Context, in *PlanEffectRequest, opts ...grpc.CallOption) (*PlanEffectResponse, error)
	// Records what the Substrate reported for one effect, including the reconciliation of an effect
	// planned under an earlier epoch. External identity and succeeded evidence never change.
	RecordEffectResult(ctx context.Context, in *RecordEffectResultRequest, opts ...grpc.CallOption) (*RecordEffectResultResponse, error)
	// Moves the operation to its next step once the current step's evidence is complete.
	AdvanceOperation(ctx context.Context, in *AdvanceOperationRequest, opts ...grpc.CallOption) (*AdvanceOperationResponse, error)
	// Parks the operation in RETRY_WAIT or BLOCKED with a finite reason.
	DeferOperation(ctx context.Context, in *DeferOperationRequest, opts ...grpc.CallOption) (*DeferOperationResponse, error)
}

type workspaceOperationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceOperationServiceClient(cc grpc.ClientConnInterface) WorkspaceOperationServiceClient {
	return &workspaceOperationServiceClient{cc}
}

func (c *workspaceOperationServiceClient) ClaimOperation(ctx context.Context, in *ClaimOperationRequest, opts ...grpc.CallOption) (*ClaimOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimOperationResponse)
	err := c.cc.Invoke(ctx, WorkspaceOperationService_ClaimOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceOperationServiceClient) PlanEffect(ctx context.Context, in *PlanEffectRequest, opts ...grpc.CallOption) (*PlanEffectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanEffectResponse)
	err := c.cc.Invoke(ctx, WorkspaceOperationService_PlanEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceOperationServiceClient) RecordEffectResult(ctx context.Context, in *RecordEffectResultRequest, opts ...grpc.CallOption) (*RecordEffectResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEffectResultResponse)
	err := c.cc.Invoke(ctx, WorkspaceOperationService_RecordEffectResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceOperationServiceClient) AdvanceOperation(ctx context.Context, in *AdvanceOperationRequest, opts ...grpc.CallOption) (*AdvanceOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvanceOperationResponse)
	err := c.cc.Invoke(ctx, WorkspaceOperationService_AdvanceOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceOperationServiceClient) DeferOperation(ctx context.Context, in *DeferOperationRequest, opts ...grpc.CallOption) (*DeferOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeferOperationResponse)
	err := c.cc.Invoke(ctx, WorkspaceOperationService_DeferOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceOperationServiceServer is the server API for WorkspaceOperationService service.
// All implementations must embed UnimplementedWorkspaceOperationServiceServer
// for forward compatibility.
//
// Runtime Workspace operations driven by the lease-holding Controller: create goes
// sandbox -> node -> clone, start goes sandbox -> node, stop and delete go quiesce -> terminate
// (-> cleanup). Each method runs the same Cloud transaction as the JSON internal API's operation
// actions. Writes are fenced by `epoch` and the operation `version`, and carry a `submission_id`
// with the same replay rules as ExecutionService. The clone step is dispatched and reported through
// ExecutionService with the operation's ID; its input and target Node are decided by Cloud.
type WorkspaceOperationServiceServer interface {
	// Takes the oldest queued, due or running operation for the caller's epoch and returns its
	// snapshot, or none. Calling it again returns the running operation with a new version.
	ClaimOperation(context.Context, *ClaimOperationRequest) (*ClaimOperationResponse, error)
	// Records the effect plan of the current step before anything is sent to the Substrate. The
	// effect ID is the Substrate idempotency key; planning the same kind for the same Workspace again
	// returns the original effect.
	PlanEffect(context.Context, *PlanEffectRequest) (*PlanEffectResponse, error)
	// Records what the Substrate reported for one effect, including the reconciliation of an effect
	// planned under an earlier epoch. External identity and succeeded evidence never change.
	RecordEffectResult(context.Context, *RecordEffectResultRequest) (*RecordEffectResultResponse, error)
	// Moves the operation to its next step once the current step's evidence is complete.
	AdvanceOperation(context.Context, *AdvanceOperationRequest) (*AdvanceOperationResponse, error)
	// Parks the operation in RETRY_WAIT or BLOCKED with a finite reason.
	DeferOperation(context.Context, *DeferOperationRequest) (*DeferOperationResponse, error)
	mustEmbedUnimplementedWorkspaceOperationServiceServer()
}

// UnimplementedWorkspaceOperationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceOperationServiceServer struct{}

func (UnimplementedWorkspaceOperationServiceServer) ClaimOperation(context.Context, *ClaimOperationRequest) (*ClaimOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimOperation not implemented")
}
func (UnimplementedWorkspaceOperationServiceServer) PlanEffect(context.Context, *PlanEffectRequest) (*PlanEffectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanEffect not implemented")
}
func (UnimplementedWorkspaceOperationServiceServer) RecordEffectResult(context.Context, *RecordEffectResultRequest) (*RecordEffectResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordEffectResult not implemented")
}
func (UnimplementedWorkspaceOperationServiceServer) AdvanceOperation(context.Context, *AdvanceOperationRequest) (*AdvanceOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdvanceOperation not implemented")
}
func (UnimplementedWorkspaceOperationServiceServer) DeferOperation(context.Context, *DeferOperationRequest) (*DeferOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeferOperation not implemented")
}
func (UnimplementedWorkspaceOperationServiceServer) mustEmbedUnimplementedWorkspaceOperationServiceServer() {
}
func (UnimplementedWorkspaceOperationServiceServer) testEmbeddedByValue() {}

// UnsafeWorkspaceOperationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceOperationServiceServer will
// result in compilation errors.
type UnsafeWorkspaceOperationServiceServer interface {
	mustEmbedUnimplementedWorkspaceOperationServiceServer()
}

func RegisterWorkspaceOperationServiceServer(s grpc.ServiceRegistrar, srv WorkspaceOperationServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkspaceOperationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceOperationService_ServiceDesc, srv)
}

func _WorkspaceOperationService_ClaimOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceOperationServiceServer).ClaimOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceOperationService_ClaimOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceOperationServiceServer).ClaimOperation(ctx, req.(*ClaimOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceOperationService_PlanEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceOperationServiceServer).PlanEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceOperationService_PlanEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceOperationServiceServer).PlanEffect(ctx, req.(*PlanEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceOperationService_RecordEffectResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEffectResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceOperationServiceServer).RecordEffectResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceOperationService_RecordEffectResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceOperationServiceServer).RecordEffectResult(ctx, req.(*RecordEffectResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceOperationService_AdvanceOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceOperationServiceServer).AdvanceOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceOperationService_AdvanceOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceOperationServiceServer).AdvanceOperation(ctx, req.(*AdvanceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceOperationService_DeferOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeferOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceOperationServiceServer).DeferOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceOperationService_DeferOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceOperationServiceServer).DeferOperation(ctx, req.(*DeferOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceOperationService_ServiceDesc is the grpc.ServiceDesc for WorkspaceOperationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceOperationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.WorkspaceOperationService",
	HandlerType: (*WorkspaceOperationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimOperation",
			Handler:    _WorkspaceOperationService_ClaimOperation_Handler,
		},
		{
			MethodName: "PlanEffect",
			Handler:    _WorkspaceOperationService_PlanEffect_Handler,
		},
		{
			MethodName: "RecordEffectResult",
			Handler:    _WorkspaceOperationService_RecordEffectResult_Handler,
		},
		{
			MethodName: "AdvanceOperation",
			Handler:    _WorkspaceOperationService_AdvanceOperation_Handler,
		},
		{
			MethodName: "DeferOperation",
			Handler:    _WorkspaceOperationService_DeferOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/operations.proto",
}
