package core

import "fmt"

// Thread message append — the public POST .../runs/{rid}/thread/messages (Thread D3, plan
// §4C.4/§4C.5/§4C.6). This is the business side of 4C: the first writer of `source='user'` Thread
// entries.
//
// Ownership (D6 invariant 7): this file writes `thread_entries` and `issue_runs.thread_state` — the
// tables the business transitions own — and reaches `thread_commands` only through the A seam
// EnqueueThreadCommand, inside the caller's transaction. It issues no SQL against `thread_commands`
// and never generates a command id.
//
// Identity separation (D-4C-06): `turn_id` is generated here (B) and written into both the entry and
// the command body, which is what lets the entry, the command and the Node's later echo correlate.
// The `command_id` is generated by A inside the seam and is derived from nothing the caller passes;
// the `seq` is allocated here from MAX(seq)+1 and is never derived from a Node sequence, and the
// `execution_id` is the Controller's and never appears in this path at all.
//
// Atomicity: the entry, the Thread state change, the command and the caller's idempotency record
// commit or roll back together. Every failure path below aborts the caller's transaction, so a
// client that retries under the same Idempotency-Key after a 503 is making a clean first request —
// not replaying a conflict and not inheriting a half-written turn.

// threadMessageTextLimit is Thread D3's bound on the total text of one appended message: 64 KiB
// measured on the decoded text, not on the request body (the JSON envelope around the text is not
// the user's message).
const threadMessageTextLimit = 64 << 10

// threadAcceptStates is Thread D4's set of states in which a new user turn is accepted. `ending` and
// `ended` are deliberately absent: D3 names them as the rejection.
var threadAcceptStates = map[string]bool{"pending": true, "active": true, "idle": true}

// threadMessageContent validates the request body's content blocks and returns the canonical block
// list the entry and the command both carry.
//
// v1 accepts text blocks only (Thread D3). An unrecognized block type is a client error and never a
// silent drop: dropping it would answer 201 while losing user content. The blocks are rebuilt rather
// than passed through so nothing outside `type`/`text` can reach the durable record.
func threadMessageContent(body Object) []Object {
	raw, ok := body["content"].([]any)
	require(ok && len(raw) > 0, 400, "invalid_json")
	blocks := make([]Object, 0, len(raw))
	total := 0
	for _, item := range raw {
		m, ok := item.(map[string]any)
		require(ok, 400, "invalid_json")
		block := Object(m)
		require(block.S("type") == "text", 400, "invalid_field_type")
		text, ok := block["text"].(string)
		require(ok, 400, "invalid_field_type")
		total += len(text)
		blocks = append(blocks, Object{"type": "text", "text": text})
	}
	// The bound is on the decoded text, so it is checked here and not at the transport limit: a body
	// that fits the transport cap can still carry too much text, and it must be refused as a message
	// that is too large rather than as malformed JSON.
	require(total <= threadMessageTextLimit, 400, "content_too_large")
	return blocks
}

// requireThreadAccepting applies the Thread POST accept matrix (Thread D3, plan §4C.4).
//
// The matrix has two kinds of row and they must not be collapsed into one status: a state the client
// can act on (`ending`/`ended` → 409 thread_closed) and a state Cloud itself guarantees cannot
// happen (an activated session with no Thread, or an activated session still reading `pending`).
// Answering the second kind with 409 would tell a client "the Thread is closed" about Cloud's own
// broken invariant, which is exactly what §4C.15 forbids — so it is a 500 that aborts the request.
//
// A2 (approved, G-024): a recorded cancellation request is Cloud's own statement that this session
// is winding down (IssueRun D6 — cancel is a *request*), so a turn accepted after it would be
// persisted and never executed. It is therefore refused with the same 409 thread_closed the closed
// states answer, and it is checked before the state matrix so no state can outrank it. The request
// changes nothing else: the run is not made terminal here, its Workspace is not deleted, and the
// `discarded` transition still belongs to Phase 5.
//
// Deliberately still absent: D-4C-03's "run Workspace is no longer live" row. The approved A2 names
// only `cancel_requested_at IS NULL` as the added conjunct, and inventing the workspace row here
// would be the kind of unapproved extension the readiness round forbids — the plan keeps it open.
func requireThreadAccepting(run Object) {
	if run.S("cancelRequestedAt") != "" {
		reject(409, "thread_closed")
	}
	state, phase := run.S("threadState"), run.S("phase")
	if threadAcceptStates[state] {
		// `pending` means StartSession declared the session and no Node record has been taken over
		// yet, which is phase `starting`. The only writer of phase `running` is the first-record
		// takeover (agent_run_thread.go), and it sets `active` in the same statement — so a running
		// run still reading `pending` is Cloud's own broken state, never something a client did.
		if state == "pending" && phase == "running" {
			panic(databaseFailure{fmt.Errorf("run %s is running with thread_state=pending; the takeover sets active", run.S("id"))})
		}
		return
	}
	switch state {
	case "ending", "ended":
		reject(409, "thread_closed")
	case "":
		// D-4C-01 materializes `pending` inside StartSession, so a run that reached 'starting' or
		// 'running' without a Thread state is an invariant break, not a client conflict (plan §4C.4)
		// — answering 409 would report a client-actionable "the Thread is closed" for Cloud's own
		// broken state. Earlier phases have no Thread at all, and a run cancelled during
		// provisioning sits in 'releasing' with no Thread state: there is genuinely nothing to
		// append to, and 409 is the client-actionable answer.
		if phase == "starting" || phase == "running" {
			panic(databaseFailure{fmt.Errorf("run %s is %s with no Thread state; D-4C-01 guarantees pending", run.S("id"), phase)})
		}
		reject(409, "thread_closed")
	default:
		panic(databaseFailure{fmt.Errorf("run %s has thread_state=%q, outside the closed set", run.S("id"), state)})
	}
}

// appendThreadMessage is the B-owned core of the Thread POST. It runs on the caller's transaction —
// the same one that carries the generic idempotency precheck and post-record — so the entry, the
// state change, the command and the idempotency record share one commit.
//
// The response is built explicitly rather than by returning the stored row: the public contract
// names seven fields, and the entry's Node columns (`node_execution_id`, `node_sequence`) are not
// part of it. A user turn has no Node identity — that is the Node's, allocated when it echoes.
func appendThreadMessage(t *transaction, s *Store, r *PublicRequest, uid string) Object {
	// Authorization is the Issue read path's own (Thread D3: "same as comments"): the caller is an
	// active tenant member — Public checked membership before dispatching here — and this resolves
	// the Issue inside the caller's tenant, so a wrong tenant or Issue is a plain not-found.
	i := issue(t, r.TenantID, r.IssueID)
	blocks := threadMessageContent(r.Body)

	require(validID(r.RunID), 404, "not_found")
	// The run is re-read authoritatively rather than taken from the path: tenant, Issue and
	// soft-deletion are all part of what makes this the Thread the caller may append to, and a run
	// outside that scope must not be distinguishable from one that does not exist.
	run := t.one(`SELECT * FROM issue_runs WHERE id=$1 AND tenant_id=$2 AND issue_id=$3 AND deleted_at IS NULL`, r.RunID, r.TenantID, i.S("id"))
	require(run != nil && run.S("executorType") == "agent", 404, "not_found")
	if binding := t.one("SELECT user_id,connection_id,revoked_at FROM run_model_bindings WHERE run_id=$1", run.S("id")); binding != nil {
		require(binding.S("userId") == uid, 403, "model_run_initiator_required")
		require(binding["revokedAt"] == nil, 409, "model_connection_unavailable")
	}
	requireThreadAccepting(run)

	runID := run.S("id")
	// seq is the run-scoped conversation order, allocated from the same MAX(seq)+1 rule the takeover
	// uses (D-023). It is not the Node's sequence and nothing derives one from the other.
	seq := t.one("SELECT COALESCE(MAX(seq),0) AS m FROM thread_entries WHERE run_id=$1", runID).N("m") + 1
	turnID := newID()
	t.exec(`
		INSERT INTO thread_entries(run_id, seq, source, kind, record, turn_id, status)
		VALUES($1,$2,'user','user_turn',$3,$4,'queued')`,
		runID, seq, jsonText(Object{"content": blocks}), turnID)
	// This entry is the whole reason a live subscriber has to re-read (Thread D5): queue the hint
	// here, at the write it describes, and let the commit decide whether it is ever published. The
	// row `run` was re-read above, so the hint's identity is the database's and not the path's.
	threadAppended(t, run)
	// The same commit also moves the Thread to `active`, so it changes the read model twice over.
	// A4's generalized hint covers both with one event, and the dedupe in threadChanged keeps the
	// entry write and the state write from publishing two hints for one commit.
	threadChanged(t, run)

	// The CAS must move exactly the row the accept matrix just approved. The matrix read and this
	// write share one transaction snapshot while the caller's advisory lock excludes every other
	// writer, so zero affected rows means some other writer moved the run under a predicate this
	// transaction did not observe — an invariant violation that rolls the whole message back, never
	// a 409 dressed up as a client conflict.
	//
	// `cancel_requested_at IS NULL` repeats the A2 conjunct the predicate above applied. Repeating it
	// is what keeps the two from drifting apart: the predicate alone could approve a row the CAS then
	// moved under a predicate nobody checked, so the guard a client is refused by and the guard the
	// write is fenced by are spelled the same way, in one place each.
	if moved := t.execRows(`
		UPDATE issue_runs SET thread_state='active', idle_since=NULL, version=version+1, updated_at=now()
		WHERE id=$1 AND thread_state IN ('pending','active','idle') AND cancel_requested_at IS NULL`, runID); moved != 1 {
		panic(databaseFailure{fmt.Errorf("thread message: run %s Thread state was not moved to active", runID)})
	}

	// The control plane's own in-transaction seam writes the command and its server-owned id
	// (D-4C-05). It cannot fail on anything the caller sent — the body is built and validated here —
	// so a refusal would be a control-plane availability failure, and the transaction rolling back
	// is what makes the retry under the same key a clean first request.
	enqueueThreadCommand(t, runID, "submit_user_turn", Object{"turnId": turnID, "content": blocks})

	entry := t.one("SELECT * FROM thread_entries WHERE run_id=$1 AND seq=$2", runID, seq)
	return Object{
		"seq":       entry.N("seq"),
		"source":    entry.S("source"),
		"kind":      entry.S("kind"),
		"record":    entry.O("record"),
		"turnId":    entry.S("turnId"),
		"status":    entry.S("status"),
		"createdAt": entry["createdAt"],
	}
}
