/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ora Cloud phase one
 * Authoritative PostgreSQL core. Simulation is separate; no production Controller/Node/Kubernetes implementation is implied.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV1MeGitIdentityBody,
  Error,
  GetApiV1MeJoinRequests200,
  GetApiV1MeJoinRequestsParams,
  GetApiV1MeSpaces200,
  GetApiV1MeSpacesParams,
  GetApiV1MeTenants200,
  GetApiV1MeTenantsParams,
  GitIdentity,
  PutApiV1MeGitIdentityBody,
  User
} from '../generated.schemas';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists use ascending UUID pagination.
 * @summary GET /api/v1/me
 */
export const getApiV1Me = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<User>(
      {url: `/api/v1/me`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1MeQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }


export const getGetApiV1MeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Me>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Me>>> = ({ signal }) => getApiV1Me(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Me>>>
export type GetApiV1MeQueryError = ErrorType<Error>


export function useGetApiV1Me<TData = Awaited<ReturnType<typeof getApiV1Me>>, TError = ErrorType<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Me>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Me>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Me<TData = Awaited<ReturnType<typeof getApiV1Me>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Me>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Me>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Me<TData = Awaited<ReturnType<typeof getApiV1Me>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/me
 */

export function useGetApiV1Me<TData = Awaited<ReturnType<typeof getApiV1Me>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Me>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Restores the default git commit identity (display name and a per-user noreply address). A stated identity is removed only at its current version, otherwise 409 version_conflict; an identity that is already the default restores as a no-op whatever version is sent, which makes a retry safe without an Idempotency-Key.
 * @summary DELETE /api/v1/me/git-identity
 */
export const deleteApiV1MeGitIdentity = (
    deleteApiV1MeGitIdentityBody: DeleteApiV1MeGitIdentityBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GitIdentity>(
      {url: `/api/v1/me/git-identity`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteApiV1MeGitIdentityBody, signal
    },
      options);
    }




export const getDeleteApiV1MeGitIdentityMutationKey = () => ['deleteApiV1MeGitIdentity'] as const;

export const getDeleteApiV1MeGitIdentityMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>, TError,DeleteApiV1MeGitIdentityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>, TError,DeleteApiV1MeGitIdentityMutationVariables, TContext> => {

const mutationKey = getDeleteApiV1MeGitIdentityMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>, DeleteApiV1MeGitIdentityMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  deleteApiV1MeGitIdentity(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1MeGitIdentityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>>
    export type DeleteApiV1MeGitIdentityMutationBody = DeleteApiV1MeGitIdentityBody
    export type DeleteApiV1MeGitIdentityMutationError = ErrorType<Error>
    export type DeleteApiV1MeGitIdentityMutationVariables = {data: DeleteApiV1MeGitIdentityBody}

    /**
 * @summary DELETE /api/v1/me/git-identity
 */
export const useDeleteApiV1MeGitIdentity = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>, TError,DeleteApiV1MeGitIdentityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1MeGitIdentity>>,
        TError,
        DeleteApiV1MeGitIdentityMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiV1MeGitIdentityMutationOptions(options), queryClient);
    }
    /**
 * Returns the git commit identity the verified user's Agent runs commit as: the stated one, or the default (display name and a per-user noreply address) with isDefault true and version 0.
 * @summary GET /api/v1/me/git-identity
 */
export const getApiV1MeGitIdentity = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GitIdentity>(
      {url: `/api/v1/me/git-identity`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV1MeGitIdentityQueryKey = () => {
    return [
    `/api/v1/me/git-identity`
    ] as const;
    }


export const getGetApiV1MeGitIdentityQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MeGitIdentityQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>> = ({ signal }) => getApiV1MeGitIdentity(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MeGitIdentityQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>>
export type GetApiV1MeGitIdentityQueryError = ErrorType<Error>


export function useGetApiV1MeGitIdentity<TData = Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError = ErrorType<Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeGitIdentity>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeGitIdentity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeGitIdentity<TData = Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeGitIdentity>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeGitIdentity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeGitIdentity<TData = Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/me/git-identity
 */

export function useGetApiV1MeGitIdentity<TData = Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeGitIdentity>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MeGitIdentityQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * States the git commit identity the verified user's Agent runs commit as. name is 1..200 characters with no line break or angle bracket, otherwise 400 invalid_git_name; email is at most 254 bytes shaped local@domain with no whitespace or angle bracket, otherwise 400 invalid_git_email. Only the shape is checked: the identity is a commit signature, never an authentication identity, and grants nothing. version is optimistic concurrency over the stated identity: 0 creates it, the current version replaces it, anything else is 409 version_conflict. Only the user can set their own identity; there is no administrator path. A session resolves the trigger user's identity when it starts, so a change applies to sessions that start afterwards.
 * @summary PUT /api/v1/me/git-identity
 */
export const putApiV1MeGitIdentity = (
    putApiV1MeGitIdentityBody: PutApiV1MeGitIdentityBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GitIdentity>(
      {url: `/api/v1/me/git-identity`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV1MeGitIdentityBody, signal
    },
      options);
    }




export const getPutApiV1MeGitIdentityMutationKey = () => ['putApiV1MeGitIdentity'] as const;

export const getPutApiV1MeGitIdentityMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1MeGitIdentity>>, TError,PutApiV1MeGitIdentityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1MeGitIdentity>>, TError,PutApiV1MeGitIdentityMutationVariables, TContext> => {

const mutationKey = getPutApiV1MeGitIdentityMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1MeGitIdentity>>, PutApiV1MeGitIdentityMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  putApiV1MeGitIdentity(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1MeGitIdentityMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1MeGitIdentity>>>
    export type PutApiV1MeGitIdentityMutationBody = PutApiV1MeGitIdentityBody
    export type PutApiV1MeGitIdentityMutationError = ErrorType<Error>
    export type PutApiV1MeGitIdentityMutationVariables = {data: PutApiV1MeGitIdentityBody}

    /**
 * @summary PUT /api/v1/me/git-identity
 */
export const usePutApiV1MeGitIdentity = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1MeGitIdentity>>, TError,PutApiV1MeGitIdentityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1MeGitIdentity>>,
        TError,
        PutApiV1MeGitIdentityMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiV1MeGitIdentityMutationOptions(options), queryClient);
    }
    /**
 * Lists the verified user's pending and decided join applications without requiring prior tenant membership.
 * @summary GET /api/v1/me/join-requests
 */
export const getApiV1MeJoinRequests = (
    params?: GetApiV1MeJoinRequestsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1MeJoinRequests200>(
      {url: `/api/v1/me/join-requests`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1MeJoinRequestsQueryKey = (params?: GetApiV1MeJoinRequestsParams,) => {
    return [
    `/api/v1/me/join-requests`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1MeJoinRequestsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError = ErrorType<Error>>(params?: GetApiV1MeJoinRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MeJoinRequestsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>> = ({ signal }) => getApiV1MeJoinRequests(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MeJoinRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>>
export type GetApiV1MeJoinRequestsQueryError = ErrorType<Error>


export function useGetApiV1MeJoinRequests<TData = Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError = ErrorType<Error>>(
 params: undefined |  GetApiV1MeJoinRequestsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeJoinRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeJoinRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeJoinRequests<TData = Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeJoinRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeJoinRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeJoinRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeJoinRequests<TData = Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeJoinRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/me/join-requests
 */

export function useGetApiV1MeJoinRequests<TData = Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeJoinRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeJoinRequests>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MeJoinRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Lists every active collaboration space whose tenant has an active membership for the verified user. A space corresponds to exactly one tenant; clients follow all pages before presenting the switcher.
 * @summary GET /api/v1/me/spaces
 */
export const getApiV1MeSpaces = (
    params?: GetApiV1MeSpacesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1MeSpaces200>(
      {url: `/api/v1/me/spaces`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1MeSpacesQueryKey = (params?: GetApiV1MeSpacesParams,) => {
    return [
    `/api/v1/me/spaces`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1MeSpacesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError = ErrorType<Error>>(params?: GetApiV1MeSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MeSpacesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MeSpaces>>> = ({ signal }) => getApiV1MeSpaces(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MeSpacesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MeSpaces>>>
export type GetApiV1MeSpacesQueryError = ErrorType<Error>


export function useGetApiV1MeSpaces<TData = Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError = ErrorType<Error>>(
 params: undefined |  GetApiV1MeSpacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeSpaces<TData = Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeSpaces>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeSpaces>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeSpaces<TData = Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/me/spaces
 */

export function useGetApiV1MeSpaces<TData = Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeSpacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeSpaces>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MeSpacesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * Public requests require a gateway service credential plus a caller-bound user credential. Active tenant membership is checked before lookup. Shared projects expose safe runtime summaries; runtime content and use require the verified creator or current tenant administrator. Conflicting mutations additionally require an effective server-confirmed control session. Mutation version conflicts return 409; a missing required version returns 428. Unknown fields are rejected. Lists page in ascending creation order; the after cursor is an exclusive tenant UUID.
 * @summary GET /api/v1/me/tenants
 */
export const getApiV1MeTenants = (
    params?: GetApiV1MeTenantsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetApiV1MeTenants200>(
      {url: `/api/v1/me/tenants`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV1MeTenantsQueryKey = (params?: GetApiV1MeTenantsParams,) => {
    return [
    `/api/v1/me/tenants`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1MeTenantsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MeTenants>>, TError = ErrorType<Error>>(params?: GetApiV1MeTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MeTenantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MeTenants>>> = ({ signal }) => getApiV1MeTenants(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MeTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MeTenants>>>
export type GetApiV1MeTenantsQueryError = ErrorType<Error>


export function useGetApiV1MeTenants<TData = Awaited<ReturnType<typeof getApiV1MeTenants>>, TError = ErrorType<Error>>(
 params: undefined |  GetApiV1MeTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeTenants<TData = Awaited<ReturnType<typeof getApiV1MeTenants>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MeTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MeTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MeTenants<TData = Awaited<ReturnType<typeof getApiV1MeTenants>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/v1/me/tenants
 */

export function useGetApiV1MeTenants<TData = Awaited<ReturnType<typeof getApiV1MeTenants>>, TError = ErrorType<Error>>(
 params?: GetApiV1MeTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MeTenants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MeTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






